### ISSUE TITLE
PaginatedList.totalCount KeyError: 'page' with large results

### ISSUE THREAD

**Issue by Twitch** [PyGithub/PyGithub#1006]
When using get_repo().totalCount on a small result set (only my own repositories) totalCount returns the repository count correctly. When querying my enterprise Github for a complete list of repositories, the following error occurs:

```bash
Traceback (most recent call last):
  File "./test-repo-list.py", line 9, in <module>
    print("Found %s repositories." % full_repo_list.totalCount)
  File "/usr/local/lib/python3.7/dist-packages/github/PaginatedList.py", line 175, in totalCount
    self.__totalCount = int(parse_qs(lastUrl)['page'][0])
KeyError: 'page'
````

I am using Python 3.7.1 and the pip-installed version 1.43.4 of PyGithub with a Github Enterprise version 2.14.7.

This is the code I have used to test this:

```python
#!/usr/bin/env python3.7
from github import Github
import os

api_token = os.getenv('GITHUB_TOKEN', None)
g = Github(base_url="https://mygithubhost.lads", login_or_token=api_token)

full_repo_list = g.get_repos()
print("Found %s repositories." % full_repo_list.totalCount)
```

I did notice, after some skimming of PaginatedList.py, that the Link headers differ between the two tests. When collecting just my own repositories, I see the "last" link returned in the link header, but when querying for all repositories I only see "next" and "first" links returned.

g.get_user().get_repos():
```json
'link':'<https://mygithubhost.lads/api/v3/user/repos?per_page=1&page=2>; rel="next", <https://mygithubhost.lads/api/v3/user/repos?per_page=1& 
page=10>; rel="last"'`
```

g.get_repos():
```json
'link':'<https://mygithubhost.lads/api/v3/repositories?per_page=1&since=112>; rel="next", <https://mygithubhost.lads/api/v3/repositories{?since}>; rel="first"'
```

I don't know what's causing this difference in behavior, though.

If I don't try to get totalCount from the object, it works as expected, but totalCount specifically seems to fail.

**Comment by Hanaasagi** [comment]
meet the same  problem
```
In [3]: g
Out[3]: <github.MainClass.Github at 0x7f56104476d8>

In [4]: g.get_repos()
Out[4]: <github.PaginatedList.PaginatedList at 0x7f56104b3940>

In [5]: x = _.totalCount
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-f22fe180df5a> in <module>
----> 1 x = _.totalCount

~/py37/lib/python3.7/site-packages/github/PaginatedList.py in totalCount(self)
    165                 links = self.__parseLinkHeader(headers)
    166                 lastUrl = links.get("last")
--> 167                 self.__totalCount = int(parse_qs(lastUrl)['page'][0])
    168         return self.__totalCount
    169

KeyError: 'page'
```

Env:
- PyGithub 1.43.4
- Python Python 3.7.1 (default, Oct 21 2018, 08:03:53) [GCC 8.2.0] on linux

**Comment by Hanaasagi** [comment]
Maybe, From the [list-all-public-repositories API](https://developer.github.com/v3/repos/#list-all-public-repositories) doc.

> Note: Pagination is powered **exclusively** by the since parameter. Use the Link header to get the URL for the next page of repositories.

It not support `per_page` parameter, so the pagination strategy is not working. But I don't know why  I no  `last` link returned in the link header.

**Comment by stoiev** [comment]
This issue could be related to the way that [PaginatedList.py](https://github.com/PyGithub/PyGithub/blob/master/github/PaginatedList.py#L170) parses `links` urls from headers.

parse_qs is executed using a full url. It fails parsing first parameter (rigth after `?`)

```python
>>> from urllib.parse import parse_qs
>>> parse_qs("https://github.com/Cobliteam/?page=11")
{'https://github.com/Cobliteam/?page': ['11']}
>>> parse_qs("https://github.com/Cobliteam/?per_page=3&page=11")
{'https://github.com/Cobliteam/?per_page': ['3'], 'page': ['11']}
```

Could this bug be reopened? Or should I open a new issue?

**Comment by SlapDrone** [comment]
Hey, just got stung by this. Anyone since managed to find a solution?

**Comment by EnricoMi** [comment]
Never seen this, reopening this issue for tracking.

**Comment by sag1sh-rezilion** [comment]
I've had a few tackles with this issue, it reappears more when using the lazy=True when creating the repo object (as an example -  r = g.get_repo('docker/docker', lazy=True); c = r.get_contributors(anon='true'); c.totalCount

**Comment by Mr-Neutr0n** [comment]
Opened a PR for this: #3450

**Comment by EnricoMi** [comment]
The `per_page` / `page` part of this issue has been fixed in #3518. The `since` part is dealt with in #3451.
