### ISSUE TITLE
Exception raised during get_api_status() 

### ISSUE THREAD

**Issue by mchrusci** [PyGithub/PyGithub#1055]
Calling `get_api_status()` raises exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mchrusci/venv3/lib/python3.5/site-packages/github/MainClass.py", line 718, in get_api_status_messages
    DEFAULT_STATUS_URL + "/api/messages.json"
  File "/home/mchrusci/venv3/lib/python3.5/site-packages/github/Requester.py", line 264, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/home/mchrusci/venv3/lib/python3.5/site-packages/github/Requester.py", line 275, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 404 {'data': '<h1>Not Found</h1>'}
```

status.github.com says it has been deprecated:
![image](https://user-images.githubusercontent.com/29942462/53645048-53023700-3c38-11e9-8e6e-9584840a66b9.png)

**Comment by sfdye** [comment]
This has been fixed in 6efd631
