### ISSUE TITLE
Exception raised in get_contents()

### ISSUE THREAD

**Issue by remram44** [PyGithub/PyGithub#1059]
```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import github
>>> gh = github.Github('mytoken')
>>> repo = gh.get_repo('VIDA-NYU/reprozip')
>>> repo.get_commit('master')
Commit(sha="a9f1ea3767e2ae357d8e67d77554845d65f4c2e7")
>>> repo.get_contents('/', 'a9f1ea3767e2ae357d8e67d77554845d65f4c2e7')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.6/site-packages/github/Repository.py", line 1479, in get_contents
    return self.get_file_contents(path, ref)
  File "lib/python3.6/site-packages/github/Repository.py", line 1503, in get_file_contents
    return github.ContentFile.ContentFile(self._requester, headers, data, completed=True)
  File "lib/python3.6/site-packages/github/GithubObject.py", line 252, in __init__
    GithubObject.__init__(self, requester, headers, attributes, completed)
  File "lib/python3.6/site-packages/github/GithubObject.py", line 86, in __init__
    self._storeAndUseAttributes(headers, attributes)
  File "lib/python3.6/site-packages/github/GithubObject.py", line 98, in _storeAndUseAttributes
    self._useAttributes(attributes)
  File "lib/python3.6/site-packages/github/ContentFile.py", line 192, in _useAttributes
    if "content" in attributes:  # pragma no branch
TypeError: argument of type 'NoneType' is not iterable
```
*[edit: removed my token (and revoked it). Doh!]*

Seems to be a regression.

**Comment by s-t-e-v-e-n-k** [comment]
I can reproduce this, looks like GitHub is returning a 302 redirect for contents of '/', currently thinking about how to solve this.

**Comment by remram44** [comment]
This is still an issue. Using stale bot when you don't reply to users is incredibly rude.

**Comment by rjackoby-r7** [comment]
Any updates?

**Comment by RomanMytsko** [comment]
I got a similar issue.
