### ISSUE TITLE
Crashing due to recursion when calling get_stats_commit_activity on large repos

### ISSUE THREAD

**Issue by Powersource** [PyGithub/PyGithub#1108]
The repo this happened on is https://github.com/chromium/chromium

```
Traceback (most recent call last):
<my code pruned>
    activity = repo.get_stats_commit_activity()
  File "/usr/local/lib/python3.6/site-packages/github/Repository.py", line 2384, in get_stats_commit_acti
vity
    self.url + "/stats/commit_activity"
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 264, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(
url)))
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 324, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 377, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 416, in __requestRaw
    return self.__requestRaw(original_cnx, verb, url, requestHeaders, input)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 416, in __requestRaw
    return self.__requestRaw(original_cnx, verb, url, requestHeaders, input)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 416, in __requestRaw
    return self.__requestRaw(original_cnx, verb, url, requestHeaders, input)
  [Previous line repeated 956 more times]
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 401, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 109, in getresponse
    r = verb(url, headers=self.headers, data=self.input, timeout=self.timeout, verify=self.verify, allow_
redirects=False)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 533, in send
    return self.build_response(request, resp)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 265, in build_response
    response = Response()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 607, in __init__
    self.headers = CaseInsensitiveDict()
  File "/usr/local/lib/python3.6/site-packages/requests/structures.py", line 44, in __init__
    self.update(data, **kwargs)
  File "/usr/local/lib/python3.6/_collections_abc.py", line 839, in update
    if isinstance(other, Mapping):
  File "/usr/local/lib/python3.6/abc.py", line 184, in __instancecheck__
    if subclass in cls._abc_cache:
  File "/usr/local/lib/python3.6/_weakrefset.py", line 75, in __contains__
    return wr in self.data
RecursionError: maximum recursion depth exceeded in comparison
```

Tbf that page [doesn't even load for me in the browser](https://github.com/chromium/chromium/graphs/contributors) but it would be nice to get a nicer (and earlier, took a while for it to crash) error message.

**Comment by Powersource** [comment]
By my measurement it takes at least 40 minutes for it to crash (and to give the user the option to catch it).
