### ISSUE TITLE
get_organizations throws exception when accessing the org 

### ISSUE THREAD

**Issue by adrianbn** [PyGithub/PyGithub#1207]
I'm getting a stack trace when trying to iterate over the organizations in my private GHE instance. The code looks like this:

```python3
g = Github(base_url=f"{GHE_URL}/api/v3", login_or_token=username, password=pwd, per_page=200)
orgs = g.get_organizations()
for i, org in enumerate(orgs):
    print(org.name)
```
And the error is as follows:
```
Traceback (most recent call last):
  File "gh_clone.py", line 67, in <module>
    print(org.name)
  File "/usr/local/lib/python3.7/site-packages/github/NamedUser.py", line 265, in name
    self._completeIfNotSet(self._name)
  File "/usr/local/lib/python3.7/site-packages/github/GithubObject.py", line 265, in _completeIfNotSet
    self._completeIfNeeded()
  File "/usr/local/lib/python3.7/site-packages/github/GithubObject.py", line 269, in _completeIfNeeded
    self.__complete()
  File "/usr/local/lib/python3.7/site-packages/github/GithubObject.py", line 274, in __complete
    self._url.value
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 276, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 292, in __customConnection
    if not url.startswith("/"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

I'm using PyGithub 1.43.8 on Python 3.7 / OSX. Other operations, such as listing all repositories directly work fine, but organizations show the error above. 

Thanks!

**Comment by adrianbn** [comment]
Never mind, this happens when the host URL has more than one trailing `/`.
