### ISSUE TITLE
TwoFactorException is not raised as expected

### ISSUE THREAD

**Issue by changhc** [PyGithub/PyGithub#1273]
### Description

If a user has 2FA enabled, when she initialises a `Github` instance with her password instead of her personal access token and then tries to perform some actions like `get_repo`, `GithubException` rather than `TwoFactorException` will be raised.

### How to reproduce

```python
>>> from github import Github
>>> name = 'username'  # username of someone with 2FA enabled
>>> password = 'password'  # password instead of personal access token
>>> gh = Github(name, password)
>>> repo = gh.get_repo('span-example')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/changhc/Desktop/projects/span/venv/lib/python3.7/site-packages/github/MainClass.py", line 294, in get_repo
    "%s%s" % (url_base, full_name_or_id)
  File "/home/changhc/Desktop/projects/span/venv/lib/python3.7/site-packages/github/Requester.py", line 276, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/home/changhc/Desktop/projects/span/venv/lib/python3.7/site-packages/github/Requester.py", line 287, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 401 {'message': 'Must specify two-factor authentication OTP code.', 'documentation_url': 'https://developer.github.com/v3/auth#working-with-two-factor-authentication'}
```

### Root cause

In the error handler of `Requester`, it checks whether a certain key is in the response headers. For 2FA-related error, it looks for `Consts.headerOTP`. The `requests` library converts all header keys to lower case, but `Consts.headerOTP` still keeps capital letters. Therefore, in the error handler this case cannot be captured as expected.

**Comment by s-t-e-v-e-n-k** [comment]
Thank you for a very detailed bug report!
