### ISSUE TITLE
Issue comments

### ISSUE THREAD

**Issue by imvieira** [PyGithub/PyGithub#1289]
Can you help me? I want to get all comments of all Github`s issues. I've read the guide here: https://buildmedia.readthedocs.org/media/pdf/pygithub/stable/pygithub.pdf 
Following the script:

```
from github import Github

g = Github(base_url="https://github.com/api/v3", login_or_token="XXX")
r = g.get_repo("ORG/REPO")
i = r.get_issues(state='open')
c = i.get_comments()

for issue in c:
    print(issue)

```

But I got the following stdout:
```
AttributeError: 'PaginatedList' object has no attribute 'get_comments'
```
I expected to see every comment from each "issue" collected by the `for`

**Comment by s-t-e-v-e-n-k** [comment]
get_issues() returns a list of issues, not one issue, you need the following:

```
from github import Github

g = Github(base_url="https://github.com/api/v3", login_or_token="XXX")
r = g.get_repo("ORG/REPO")
for issue in r.get_issues(state='open'):
    for comment in issue.get_comments():
        print(comment)
```

**Comment by imvieira** [comment]
@s-t-e-v-e-n-k Seems worked. 

```
import github

gh = github.Github()
repo = gh.get_repo('PyGithub/PyGithub')


for issue in repo.get_issues(state='open'):
    for comment in issue.get_comments():
        print(comment)
```
However, I got the error after one successful tentative:
```

Traceback (most recent call last):
  File "c:/Users/IgorMonteiroVieira/Desktop/teste.py", line 4, in <module>
    repo = gh.get_repo('PyGithub/PyGithub')
  File "C:\Users\IgorMonteiroVieira\AppData\Local\Programs\Python\Python37\lib\site-packages\github\MainClass.py", line 292, in get_repo
    "%s%s" % (url_base, full_name_or_id)
  File "C:\Users\IgorMonteiroVieira\AppData\Local\Programs\Python\Python37\lib\site-packages\github\Requester.py", line 268, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "C:\Users\IgorMonteiroVieira\AppData\Local\Programs\Python\Python37\lib\site-packages\github\Requester.py", line 279, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for 177.131.81.29. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", "documentation_url": "https://developer.github.com/v3/#rate-limiting"}
```

**Comment by imvieira** [comment]
```
c:/Users/IgorMonteiroVieira/Desktop/teste.py
IssueComment(user=NamedUser(login="TravisBuddy"), id=554605599)
IssueComment(user=NamedUser(login="codecov-io"), id=554605603)
IssueComment(user=NamedUser(login="TravisBuddy"), id=552956573)
IssueComment(user=NamedUser(login="codecov-io"), id=552956723)
IssueComment(user=NamedUser(login="s-t-e-v-e-n-k"), id=553725796)
IssueComment(user=NamedUser(login="chr1st1ank"), id=554653465)
IssueComment(user=NamedUser(login="s-t-e-v-e-n-k"), id=552666654)
IssueComment(user=NamedUser(login="TravisBuddy"), id=551177456)
IssueComment(user=NamedUser(login="codecov-io"), id=551177473)
IssueComment(user=NamedUser(login="s-t-e-v-e-n-k"), id=551384536)
IssueComment(user=NamedUser(login="TravisBuddy"), id=551480268)
IssueComment(user=NamedUser(login="tlong123"), id=551490794)
IssueComment(user=NamedUser(login="s-t-e-v-e-n-k"), id=551540758)
IssueComment(user=NamedUser(login="TravisBuddy"), id=550945246)
IssueComment(user=NamedUser(login="codecov-io"), id=550945343)
IssueComment(user=NamedUser(login="s-t-e-v-e-n-k"), id=552327242)
IssueComment(user=NamedUser(login="TravisBuddy"), id=545197178)
IssueComment(user=NamedUser(login="TravisBuddy"), id=545199704)
IssueComment(user=NamedUser(login="TravisBuddy"), id=545448946)
IssueComment(user=NamedUser(login="LeoQuote"), id=545434834)
IssueComment(user=NamedUser(login="TravisBuddy"), id=542561552)
IssueComment(user=NamedUser(login="TravisBuddy"), id=542991176)
IssueComment(user=NamedUser(login="TravisBuddy"), id=542995022)
IssueComment(user=NamedUser(login="codecov-io"), id=542995025)
IssueComment(user=NamedUser(login="s-t-e-v-e-n-k"), id=548301055)
IssueComment(user=NamedUser(login="surajjacob"), id=541223483)
IssueComment(user=NamedUser(login="maxlovic"), id=541339113)
Traceback (most recent call last):
  File "c:/Users/IgorMonteiroVieira/Desktop/teste.py", line 8, in <module>
  File "C:\Users\IgorMonteiroVieira\AppData\Local\Programs\Python\Python37\lib\site-packages\github\PaginatedList.py", line 61, in __iter__
    newElements = self._grow()
  File "C:\Users\IgorMonteiroVieira\AppData\Local\Programs\Python\Python37\lib\site-packages\github\PaginatedList.py", line 73, in _grow
    newElements = self._fetchNextPage()
  File "C:\Users\IgorMonteiroVieira\AppData\Local\Programs\Python\Python37\lib\site-packages\github\PaginatedList.py", line 198, in _fetchNextPage
    headers=self.__headers
  File "C:\Users\IgorMonteiroVieira\AppData\Local\Programs\Python\Python37\lib\site-packages\github\Requester.py", line 268, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "C:\Users\IgorMonteiroVieira\AppData\Local\Programs\Python\Python37\lib\site-packages\github\Requester.py", line 279, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for 177.131.81.29. (But here's the good news: Authenticated requests get a higher rate limit. Check outPS
```


@s-t-e-v-e-n-k Steven, thanks for helping. I confess I was struggling to figure out a way to get the comments of an "issue".

I ran the script and I expected to see the comments in text. However, the output did not show the commentaries, but only showed the userids. Do you know how to show all the commentaries instead of only the userIDs? Thank you...

**Comment by imvieira** [comment]
```
import github

gh = github.Github()
repo = gh.get_repo('PyGithub/PyGithub')


for issue in repo.get_issues(state='open'):
    for comment in issue.get_comments():
        print(comment)

```

**Comment by s-t-e-v-e-n-k** [comment]
Printing comment will print a representation of the *object*, not the comments themselves. You want:

```
print(comment.body)
```

Which is documented at https://pygithub.readthedocs.io/en/latest/github_objects/IssueComment.html

**Comment by imvieira** [comment]
Worked properly! 
@s-t-e-v-e-n-k How can I download the attachments from each commentary?

**Comment by imvieira** [comment]
I ran `print(comment.body)` . After some outputs, the error returned was the following:

@s-t-e-v-e-n-k 
```

  File "C:\Users\IgorMonteiroVieira\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u27a4' in position 0: character maps to <undefined>

```

**Comment by imvieira** [comment]
Solved with:

```

        print(comment.body.encode("utf-8"))
```
