### ISSUE TITLE
create_fork fails with UnknownObjectException

### ISSUE THREAD

**Issue by HebaruSan** [PyGithub/PyGithub#1320]
OS: Ubuntu 19.10
python3-github version 1.40-1

I'd like to fork a repo. Here's my code:

```python
#!/usr/bin/env python3
import github
token = 'my token removed for privacy'
gh = github.Github(token)
src_repo = gh.get_user('linuxgurugamer').get_repo('abcors')
gh.get_user().create_fork(src_repo)
```

Exception:

```
$ ./test-gh-mk-fork.py 
Traceback (most recent call last):
  File "./test-gh-mk-fork.py", line 9, in <module>
    gh.get_user().create_fork(src_repo)
  File "/usr/lib/python3/dist-packages/github/AuthenticatedUser.py", line 469, in create_fork
    "/repos/" + repo.owner.login + "/" + repo.name + "/forks"
  File "/usr/lib/python3/dist-packages/github/Requester.py", line 260, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/lib/python3/dist-packages/github/Requester.py", line 271, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/forks/#create-a-fork'}
```

I don't understand what this is telling me. Is there something wrong with the above code?

**Comment by HebaruSan** [comment]
I just needed to check this box in the token's settings!

![image](https://user-images.githubusercontent.com/1559108/71136879-db53c780-21cb-11ea-966e-457100277fba.png)

Sorry for wasting your time, and thanks for a great library!
