### ISSUE TITLE
'latin-1' codec can't encode characters in position 6-7: ordinal not in range(256)

### ISSUE THREAD

**Issue by vmayoral** [PyGithub/PyGithub#1523]
Version  1.51 has conflicts when fetching individual repositories by name:

```python
>>> from github import Github
>>> import os
>>> token = os.environ["GITHUB_TOKEN"]
>>> g = Github(token)
>>> repo = g.get_repo("PyGithub/PyGithub")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/github/MainClass.py", line 325, in get_repo
    "GET", "%s%s" % (url_base, full_name_or_id)
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 410, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 472, in __requestEncode
    cnx, verb, url, requestHeaders, encoded_input
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 498, in __requestRaw
    response = cnx.getresponse()
  File "/usr/local/lib/python3.6/dist-packages/github/Requester.py", line 116, in getresponse
    allow_redirects=False,
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1305, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.6/http/client.py", line 1237, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 6-7: ordinal not in range(256)
```

```bash
pip3 show pygithub
Name: PyGithub
Version: 1.51
Summary: Use the full Github API v3
Home-page: http://pygithub.readthedocs.io/en/latest/
Author: Vincent Jacques
Author-email: vincent@vincent-jacques.net
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires: requests, pyjwt, deprecated
```

**Comment by vmayoral** [comment]
Validated this occurs as well with other versions, e.g. `1.47`

**Comment by vmayoral** [comment]
I haven't been able to reproduce it in a clean environment (with OS virtualization) so I'm closing this for now as an isolated (I guess dependency-related) issue.
