### ISSUE TITLE
Stack trace in `get_required_status_checks` when not enabled.

### ISSUE THREAD

**Issue by martinusnel** [PyGithub/PyGithub#1548]
Calling `get_required_status_checks ` (https://pygithub.readthedocs.io/en/latest/github_objects/Branch.html#github.Branch.Branch.get_required_status_checks) with required status checks disabled produces a stack trace:
```
>>> master.get_required_status_checks()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mnel/.pyenv/versions/3.6.8/lib/python3.6/site-packages/github/Branch.py", line 264, in get_required_status_checks
    "GET", self.protection_url + "/required_status_checks"
  File "/home/mnel/.pyenv/versions/3.6.8/lib/python3.6/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/home/mnel/.pyenv/versions/3.6.8/lib/python3.6/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 404 {"message": "Required status checks not enabled", "documentation_url": "https://developer.github.com/v3/repos/branches/#get-required-status-checks-of-protected-branch"}
>>> 
```
I would have expected a simple `false`.

Calling `get_required_status_checks ` with required status checks enabled produces good output.
```
>>> master.get_required_status_checks()
RequiredStatusChecks(url="https://api.github.com/repos/some_repo/branches/master/protection/required_status_checks", strict=True)
```

**Comment by s-t-e-v-e-n-k** [comment]
This is actually the pattern we use all over the code base. We have never implemented a look-before-you-leap mentality, leaving it up the GitHub API itself on what data it returns -- even if that response is a 400 or a 404. While yes, I can understand your point of view, I'm against such a large change to the code base.
