### ISSUE TITLE
[BUG] PyGithub uses incorrect API endpoint when fetching organization projects

### ISSUE THREAD

**Issue by mbestavros** [PyGithub/PyGithub#1598]
I'm using PyGithub to write some automation around org-level Github projects.

However, I'm running into a problem when I try and fetch a project associated with an organization. See below as an example:

```python
github = Github(token)
repo = github.get_repo(repo_name)
org_projects = repo.organization.get_projects()
project = org_projects[0]
```

When running this code, I encounter a `GithubException` with `422` as the error:

```python
Traceback (most recent call last):
  File "scripts/exec", line 4, in <module>
    sprint_project = org_projects[0]
  File "/home/runner/.local/lib/python3.6/site-packages/github/PaginatedList.py", line 50, in __getitem__
    self.__fetchToIndex(index)
  File "/home/runner/.local/lib/python3.6/site-packages/github/PaginatedList.py", line 68, in __fetchToIndex
    self._grow()
  File "/home/runner/.local/lib/python3.6/site-packages/github/PaginatedList.py", line 71, in _grow
    newElements = self._fetchNextPage()
  File "/home/runner/.local/lib/python3.6/site-packages/github/PaginatedList.py", line 201, in _fetchNextPage
    "GET", self.__nextUrl, parameters=self.__nextParams, headers=self.__headers
  File "/home/runner/.local/lib/python3.6/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/home/runner/.local/lib/python3.6/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "ID 67755615 is an Organization, not a User. Change your request to use Organization endpoints.", "documentation_url": "https://developer.github.com/v3/projects/"}
```

I'm reading this as PyGithub using the incorrect endpoint for fetching organization projects internally. Or am I mistaken?

Happy to help further if needed.

**Comment by s-t-e-v-e-n-k** [comment]
We've had this come up a few times -- what happens if you fetch the org directly, rather than via a repo -- GitHub seems to assume that every owner of a repo is a user even if it's a org, with hilarious results. https://pygithub.readthedocs.io/en/latest/github.html#github.MainClass.Github.get_organization
