### ISSUE TITLE
get_git_refs() vs get_git_ref('xxxxx')

### ISSUE THREAD

**Issue by xpdable** [PyGithub/PyGithub#1647]
While I am implementing #1628 there is a strange issue.
To get master branch GitRef, I used two different way:
```python
# function 1
master_ref1 = repo.get_git_ref('/heads/master')
```
and 
```python
# function 2
master_refs = self.github_repo.get_git_refs().get_page(0)
master_ref = None
for ref in master_refs:
    if ref.ref == "refs/heads/{}".format("master"):
        master_ref = ref
```

Then I try to commit some files with the example of below script ( same as #1628 )
```python
import github
g = github.Github(base_url="https://git.mycompany.com/api/v3",login_or_token="mytoken")
repo = g.get_repo('myorg/myrepo')
blob = repo.create_git_blob("file-content", "utf-8")
element = github.InputGitTreeElement(path="path-in-repo.ext", mode='100644', type='blob', sha=blob.sha)
head_sha = repo.get_branch('master').commit.sha
base_tree = repo.get_git_tree(sha=head_sha)
tree = repo.create_git_tree([element], base_tree)
parent = repo.get_git_commit(sha=head_sha)
commit = repo.create_git_commit("commit_message", tree, [parent])
# function 1 or function 2
master_ref.edit(sha=commit.sha)
```
And it performs differently:
```
function 1 return:
>>> master_ref.edit(sha=commit.sha)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/github/GitRef.py", line 91, in edit
    "PATCH", self.url, input=post_parameters
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 500 null
```
While `function 2` works correctly.

Could some one explain or know what is the root cause of this?
Thanks.

**Comment by s-t-e-v-e-n-k** [comment]
The leading slash seems to be the cause -- try ``master_ref1 = repo.get_git_ref('heads/master')``

**Comment by xpdable** [comment]
> The leading slash seems to be the cause -- try `master_ref1 = repo.get_git_ref('heads/master')`

Unfortunately, it is not the case...
I use `master_ref = repo.get_git_ref('heads/master')` and get another error response:
```
409 {"message": "Git Repository is empty.", "documentation_url": "https://developer.github.com/enterprise/2.21/v3/git/commits/#create-a-commit"}
```
