### ISSUE TITLE
unknownObjectException on Organization object: get a team by name

### ISSUE THREAD

**Issue by ChaiBapchya** [PyGithub/PyGithub#1685]
I've a github object which is properly authenticated.
With the github object, I'm able to access the pull-requests, the organization.
However, I am unable to get the team name

Reproduce:
```
    github_obj = GithubObj(apply_secret=True) #uses personal access token
    org=github_obj.github_object.get_organization('apache')
    print(org)
    print(github_obj.github_object.get_repo('apache/incubator-mxnet'))
    print(github_obj.github_object.get_repo('apache/incubator-mxnet').get_pull(int(19004)))
    print(org.get_team(<team-id>))
```

Output
```
Organization(login="apache")
Repository(full_name="apache/incubator-mxnet")
PullRequest(title="Numpy Random Ops Fix & Testcases", number=19004)
Traceback (most recent call last):
  File "test.py", line 144, in <module>
    check_ci_failure()
  File "test.py", line 92, in check_ci_failure
    load_and_test(data)
  File "test.py", line 71, in load_and_test
    print(org.get_team(<team-id>))
  File "/usr/local/lib/python3.7/site-packages/github/Organization.py", line 971, in get_team
    headers, data = self._requester.requestJsonAndCheck("GET", "/teams/" + str(id))
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/teams#get-a-team-by-name"}
```

However, outside this project, on my shell I'm able to access the organization object properly. 

What's the difference? What's the issue?

**Comment by ChaiBapchya** [comment]
Nvermind, I overrode the personal access token internally causing issues while accessing the team
