### ISSUE TITLE
Can't create repo on AuthenticatedUser, always returns 404

### ISSUE THREAD

**Issue by marcodarko** [PyGithub/PyGithub#1703]
I've created a detailed [question](https://stackoverflow.com/questions/64019094/creating-repo-on-authenticated-user-with-pygithub-throws-exception) on StackOverflow as well hoping to get an answer quickly. 
I'm authenticating with my user token. 

and the complete traceback error is here: 

      `[ERROR tornado.application web:1599] Exception in exception handler
    Traceback (most recent call last):
      File "/Users/marcocano/Desktop/tsri/discovery-app/discovery/web/api/github.py", line 43, in post
        repo = auth_user.create_repo(repo_name)
      File "/Users/marcocano/Desktop/tsri/discovery-app/env/lib/python3.6/site-packages/github/AuthenticatedUser.py", line 679, in create_repo
        "POST", "/user/repos", input=post_parameters
      File "/Users/marcocano/Desktop/tsri/discovery-app/env/lib/python3.6/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
        verb, url, parameters, headers, input, self.__customConnection(url)
      File "/Users/marcocano/Desktop/tsri/discovery-app/env/lib/python3.6/site-packages/github/Requester.py", line 342, in __check
        raise self.__createException(status, responseHeaders, output)
    github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-repository-for-the-authenticated-user"}

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/marcocano/Desktop/tsri/discovery-app/env/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/marcocano/Desktop/tsri/discovery-app/discovery/web/api/base.py", line 26, in _
        return func(self, *args, **kwargs)
      File "/Users/marcocano/Desktop/tsri/discovery-app/discovery/web/api/github.py", line 46, in post
        raise HTTPError(400, reason=e)
    tornado.web.HTTPError: HTTP 400: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-repository-for-the-authenticated-user"}

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/marcocano/Desktop/tsri/discovery-app/env/lib/python3.6/site-packages/tornado/web.py", line 1597, in _execute
        self._handle_request_exception(e)
      File "/Users/marcocano/Desktop/tsri/discovery-app/env/lib/python3.6/site-packages/tornado/web.py", line 1648, in _handle_request_exception
        self.send_error(e.status_code, exc_info=sys.exc_info())
      File "/Users/marcocano/Desktop/tsri/discovery-app/env/lib/python3.6/site-packages/tornado/web.py", line 1110, in send_error
        self.set_status(status_code, reason=reason)
      File "/Users/marcocano/Desktop/tsri/discovery-app/env/lib/python3.6/site-packages/tornado/web.py", line 326, in set_status
        self._reason = escape.native_str(reason)
      File "/Users/marcocano/Desktop/tsri/discovery-app/env/lib/python3.6/site-packages/tornado/escape.py", line 215, in to_unicode
        "Expected bytes, unicode, or None; got %r" % type(value)
    TypeError: Expected bytes, unicode, or None; got <class 'github.GithubException.UnknownObjectException'>`

This is my code and everything works fine until I call create_repo:

        `if self.request.headers['Content-Type'] == 'application/json':
                self.args = json.loads(self.request.body)
            repo_name = self.args.get('name', None)
            if not repo_name:
                raise HTTPError(400, reason=f"Required parameter 'name' not provided")

        user = json.loads(self.get_secure_cookie("user"))
        # signin with token
        g = Github(user['access_token'])
        # authenticated user
        auth_user = g.get_user()
        if auth_user.login:
            try:
                print('auth_user',auth_user)
                repo = auth_user.create_repo(repo_name)
                print(repo)
            except GithubException as e:
                raise HTTPError(400, reason=e)
            except Exception as exc:  # unexpected
                raise HTTPError(500, reason=str(exc))

        else:
            raise HTTPError(400, reason=f"Unable to authenticate user")

        return repo`

**Comment by marcodarko** [comment]
Seems to be a token scope issue actually, different error but this issue's main topic is not relevant anymore. here's the docs I found helpful https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/
