### ISSUE TITLE
AssertionError: None

### ISSUE THREAD

**Issue by joe733** [PyGithub/PyGithub#1722]
I'm trying to access the profile repo (user/user) using GitHub token which is passed as environment variable.

`main.py`
```py
ghtoken = os.getenv('INPUT_GH_TOKEN') # $ export INPUT_GH_TOKEN=my_token

...

if __name__ == '__main__':
    g = Github(ghtoken)
    try:
        repo = g.get_repo(repository) # if '' should use profile user/user
    except GithubException:
        print("Authentication Error. Try saving a GitHub Token in your Repo Secrets or Use the GitHub Actions Token, which is automatically used by the action.")
```

But when I run `python main.py` I'm greeted with:
```py
Traceback (most recent call last):
  File "main.py", line 95, in <module>
    repo = g.get_repo(repository)
  File "/home/joe733/anaconda3/envs/wakareadme/lib/python3.8/site-packages/github/MainClass.py", line 317, in get_repo
    assert isinstance(full_name_or_id, (str, int)), full_name_or_id
AssertionError: None
```

How do I solve this?

**Comment by s-t-e-v-e-n-k** [comment]
Your issue is the variable `repository` is None, instead of an a string or an integer. How are you setting it?

**Comment by joe733** [comment]
`repository` is also taken from the env.. but it happened to be `None`. Thanks for pointing out! Sorry for the trouble.
