### ISSUE TITLE
Syntax error due to pyjwt-2.0.0

### ISSUE THREAD

**Issue by PaulLesur** [PyGithub/PyGithub#1796]
Hello ! 
We are facing syntax errors using PyGithub since pyjwt version 2.0.0.

```
Traceback (most recent call last):
  File "ci-tools/get_corresponding_tag.py", line 4, in <module>
    from github import Github
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/site-packages/github/__init__.py", line 58, in <module>
    from github.MainClass import Github, GithubIntegration
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/site-packages/github/MainClass.py", line 57, in <module>
    import jwt
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/site-packages/jwt/__init__.py", line 1, in <module>
    from .api_jws import (
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/site-packages/jwt/api_jws.py", line 134
    **kwargs,
            ^
SyntaxError: invalid syntax
```

A temporary solution is to install this dependency with a version inferior to 2.0.0

**Comment by jambon69** [comment]
:+1:

**Comment by gturbat** [comment]
:+1:

**Comment by xupefei** [comment]
We are seeing this issue too in Python 3.5. For some reason, `pip3` choose to install `pyjwt 2.0.0` even when https://pypi.org/project/PyJWT/ says 2.0.0 "Requires: Python >=3.6".
