### ISSUE TITLE
Return None for get_readme()

### ISSUE THREAD

**Issue by xtuchyna** [PyGithub/PyGithub#1829]
Currently, when you try to call `get_readme()` on a repository that does not contain a README file, an exception occurs:
```
>>> r.get_readme()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xtuchyna/.local/share/virtualenvs/SrcOpsMetrics-Vwmk3Tpf/lib/python3.8/site-packages/github/Repository.py", line 2809, in get_readme
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/xtuchyna/.local/share/virtualenvs/SrcOpsMetrics-Vwmk3Tpf/lib/python3.8/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/home/xtuchyna/.local/share/virtualenvs/SrcOpsMetrics-Vwmk3Tpf/lib/python3.8/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-repository-readme"}
>>> 
```

I think that it would be more practical to return `None` instead of raising exception, WDYT?

**Comment by s-t-e-v-e-n-k** [comment]
We try really really hard to return what GitHub returns -- even if that results in an raised exception.
