### ISSUE TITLE
I have a problem for import PyGithub

### ISSUE THREAD

**Issue by sunshine666** [PyGithub/PyGithub#1845]
root@sun-VirtualBox:/home/sun/getgit# cat /home/sun/getgit/t.py
from github import Github
root@sun-VirtualBox:/home/sun/getgit# python /home/sun/getgit/t.py
Traceback (most recent call last):
  File "/home/sun/getgit/t.py", line 1, in <module>
    from github import Github
  File "/usr/local/lib/python2.7/dist-packages/github/__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "/usr/local/lib/python2.7/dist-packages/github/MainClass.py", line 340
    url = f"{url_base}{full_name_or_id}"
                                       ^
SyntaxError: invalid syntax

this is error for run the code, what's wrong,can someone help me

**Comment by s-t-e-v-e-n-k** [comment]
Python 2.7 is no longer supported, either use PyGithub 1.45 or upgrade to Python 3.6

**Comment by mamh2021** [comment]
`
Python 2.7.12 (default, Mar  1 2021, 11:38:31) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import      github
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/github/__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "/usr/local/lib/python2.7/dist-packages/github/MainClass.py", line 340
    url = f"{url_base}{full_name_or_id}"
                                       ^
SyntaxError: invalid syntax

`

**Comment by mamh2021** [comment]
```
Python 3.5.2 (default, Jan 26 2021, 13:30:48) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import github
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/github/__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "/usr/local/lib/python3.5/dist-packages/github/MainClass.py", line 340
    url = f"{url_base}{full_name_or_id}"
                                       ^
SyntaxError: invalid syntax

```

**Comment by s-t-e-v-e-n-k** [comment]
Python 2.7 and Python 3.5 are no longer supported. Please don't comment on closed issues.
