### ISSUE TITLE
Auth failure: `github.GithubException.GithubException: 401 {"message": "Must authenticate to access this API."...}`

### ISSUE THREAD

**Issue by scottdangelo** [PyGithub/PyGithub#1865]
I'm getting an auth failure where this script used to work:
```
#! /usr/bin/env python

import os
from github import Github

REPO = os.environ.get('REPO')
GH_TOKEN = os.environ.get('TOKEN')

g = Github(base_url="https://github.ibm.com/api/v3", login_or_token=GH_TOKEN)
repo = g.get_repo(REPO)
print(repo.name)
```

The Traceback is:
```
Traceback (most recent call last):
  File "/Users/scott/gitRepos/scottdangelo/scottsTools/GitTools/create-new-version-issues.py", line 32, in <module>
    repo = g.get_repo(REPO)
  File "/usr/local/lib/python3.9/site-packages/github/MainClass.py", line 345, in get_repo
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 401 {"message": "Must authenticate to access this API.", "documentation_url": "https://developer.github.com/enterprise/2.21/v3"}
```

I see that others have this same issue on #1119 , which was closed a while back, but there are current comments from <24 hours ago.

**Comment by s-t-e-v-e-n-k** [comment]
Commenting on closed issues is not a good way to get our attention.

This seems to me that the base_url might have moved -- and you're getting redirected instead of authenticated.

```
import github
github.enable_console_debug_logging()
...
g = github.Github(...)
```

might help you shed more light on what is going on.

**Comment by AndyReiblein** [comment]
Has anyone solved this yet ? x_x Im sitting with the same issue :/

**Comment by iwangliguo** [comment]
I have the same problem now, is there any solutions？ thanks.
