### ISSUE TITLE
Bug in repr(PublicKey)

### ISSUE THREAD

**Issue by schlitzered** [PyGithub/PyGithub#1878]
hi there.

there is a bug in "repo.get_public_key".

i found this bug by trying to use "repo.create_secret", which failed because of this issue

```
repo.get_public_key()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/sschultchen/PycharmProjects/IAC_Main/venv/lib/python3.9/site-packages/github/PublicKey.py", line 55, in __repr__
    return self.get__repr__({"key_id": self._key_id.value, "key": self._key.value})
  File "/Users/sschultchen/PycharmProjects/IAC_Main/venv/lib/python3.9/site-packages/github/GithubObject.py", line 62, in value
    raise GithubException.BadAttributeException(
github.GithubException.BadAttributeException: (1, <class 'str'>, None)
```

i guess the reason for this might be that the pygithub implementation assumes that "key_id" is a string, but it actually is a integer.

at least, the github api gives me an integer, and not a string for this attribute.

**Comment by s-t-e-v-e-n-k** [comment]
Just testing this myself on the public GitHub, I get back key_id as a string?

**Comment by schlitzered** [comment]
hmm, i tested this against a github enterprise instance. i can check again tomorrow, and maybe attach the result from the get request.

**Comment by s-t-e-v-e-n-k** [comment]
Sounds great, thanks.

**Comment by schlitzered** [comment]
here is the output of 'repo._requester.requestJsonAndCheck("GET", f"{repo.url}/actions/secrets/public-key")'

there you can see that "key_id" is an integer.

i also checked with github.com, and there key_id is indeed a string

```
[
    {
        "access-control-allow-origin": "*",
        "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset",
        "cache-control": "private, max-age=60, s-maxage=60",
        "content-encoding": "gzip",
        "content-security-policy": "default-src 'none'",
        "content-type": "application/json; charset=utf-8",
        "date": "Fri, 19 Mar 2021 07:13:08 GMT",
        "etag": "W/\"db09a86f9a30ab1d2f7e0239a47718a3\"",
        "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
        "server": "GitHub.com",
        "status": "200 OK",
        "strict-transport-security": "max-age=31536000; includeSubdomains",
        "transfer-encoding": "chunked",
        "vary": "Accept, Authorization, Cookie, X-GitHub-OTP",
        "x-accepted-oauth-scopes": "",
        "x-content-type-options": "nosniff",
        "x-frame-options": "deny",
        "x-github-enterprise-version": "2.22.6",
        "x-github-media-type": "github.v3; format=json",
        "x-github-request-id": "627be4e4-56d1-42da-88cf-1c09a2dde2d3",
        "x-oauth-scopes": "admin:gpg_key, admin:org, admin:org_hook, admin:pre_receive_hook, admin:public_key, admin:repo_hook, delete_repo, gist, notifications, repo, user, write:discussion",
        "x-ratelimit-limit": "5000",
        "x-ratelimit-remaining": "4997",
        "x-ratelimit-reset": "1616141558",
        "x-runtime-rack": "0.035888",
        "x-xss-protection": "1; mode=block"
    },
    {
        "key": "<secret_removed>",
        "key_id": 1
    }
]
```

**Comment by schlitzered** [comment]
as a quickfix, i replaces the "repo.get_public_key" method with this:

```
    def get_public_key(self):
        """
        :calls: `GET /repos/:owner/:repo/actions/secrets/public-key <https://docs.github.com/en/rest/reference/actions#get-a-repository-public-key>`_
        :rtype: :class:`github.PublicKey.PublicKey`
        """
        headers, data = self._requester.requestJsonAndCheck(
            "GET", f"{self.url}/actions/secrets/public-key"
        )
        data['key_id'] = str(data['key_id'])
        return github.PublicKey.PublicKey(
            self._requester, headers, data, completed=True
        )
```

the relevant change here is this:

```
data['key_id'] = str(data['key_id'])
```

**Comment by s-t-e-v-e-n-k** [comment]
Ah, I'm sorry, I missed your helpful debugging.

That is a workaround, not a bad one, but I think the correct thing to do in this case is say key_id can be int or str and deal correctly in either case.

**Comment by schlitzered** [comment]
whatever you see fit. i would offer to do it myself, but i have no clue how a proper implementation would look like to match the style of this lib.
