### ISSUE TITLE
How to remove character limit 

### ISSUE THREAD

**Issue by johnnyjacq16** [PyGithub/PyGithub#1906]
Hi s-t-e-v-e-n-k 
How to remove the character limit of 65536 on issue body.

Traceback (most recent call last):
  File "<stdin>", line 4511, in <module>
  File "/usr/local/lib/python3.6/site-packages/github/Repository.py", line 1218, in create_issue
    "POST", self.url + "/issues", input=post_parameters
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.6/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "Issue", "code": "custom", "field": "body", "message": "body is too long (maximum is 65536 characters)"}], "documentation_url": "https://docs.github.com/rest/reference/issues#create-an-issue"}

![image](https://user-images.githubusercontent.com/46075870/113489492-799c9700-94bc-11eb-8adc-88658bc49041.png)

**Comment by s-t-e-v-e-n-k** [comment]
That limit is enforced by GitHub, so it can not be removed.
