### ISSUE TITLE
Receiving Server Error on specific Pull Request events iteration

### ISSUE THREAD

**Issue by xtuchyna** [PyGithub/PyGithub#1918]
**Description**
Hello!

I was trying to gather some data from `scikit-learn` repository Pull Requests, however I came across a specific one (https://github.com/scikit-learn/scikit-learn/pull/4294) on which the iteration through all events causes  `github.GithubException.GithubException: 502 {"message": "Server Error"}`.

**To reproduce**
```
from github import Github
gh = Github(login_or_token=<github_token>)

sl = gh.get_repo("scikit-learn/scikit-learn")
pr = sl.get_pull(4294)
issue = pr.as_issue()

events = issue.get_timeline()
for event in issue.get_timeline():
    print(e.event)
```
**LOG**
```
>>> for e in events:
...     print(e.event)
... 
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
commented
head_ref_force_pushed
commented
commented
commented
commented
mentioned
subscribed
commented
commented
commented
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
commented
mentioned
subscribed
head_ref_force_pushed
renamed
commented
renamed
commented
commented
head_ref_force_pushed
head_ref_force_pushed
mentioned
subscribed
line-commented
commented
commented
mentioned
subscribed
head_ref_force_pushed
head_ref_force_pushed
commented
head_ref_force_pushed
line-commented
line-commented
commented
commented
commented
mentioned
subscribed
commented
commented
commented
commented
commented
commented
head_ref_force_pushed
commented
mentioned
subscribed
mentioned
subscribed
commented
mentioned
subscribed
mentioned
subscribed
commented
commented
commented
commented
commented
commented
cross-referenced
commented
commented
commented
commented
mentioned
subscribed
commented
commented
commented
cross-referenced
commented
commented
mentioned
subscribed
commented
mentioned
subscribed
mentioned
subscribed
commented
mentioned
subscribed
commented
mentioned
subscribed
commented
mentioned
subscribed
mentioned
subscribed
commented
mentioned
subscribed
mentioned
subscribed
commented
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
commented
mentioned
subscribed
mentioned
subscribed
commented
commented
mentioned
subscribed
commented
commented
mentioned
subscribed
commented
commented
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
commented
head_ref_force_pushed
commented
commented
commented
head_ref_force_pushed
commented
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
line-commented
line-commented
commented
line-commented
commented
mentioned
subscribed
line-commented
renamed
line-commented
line-commented
line-commented
mentioned
subscribed
mentioned
subscribed
line-commented
line-commented
line-commented
commented
mentioned
subscribed
cross-referenced
head_ref_force_pushed
head_ref_force_pushed
head_ref_force_pushed
commented
cross-referenced
head_ref_force_pushed
head_ref_force_pushed
head_ref_force_pushed
head_ref_force_pushed
line-commented
commented
line-commented
cross-referenced
commented
mentioned
subscribed
closed
reopened
commented
line-commented
line-commented
line-commented
line-commented
line-commented
line-commented
line-commented
line-commented
commented
commented
commented
commented
commented
commented
commented
commented
commented
commented
cross-referenced
commented
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
commented
commented
commented
commented
commented
commented
commented
commented
commented
commented
commented
mentioned
subscribed
mentioned
subscribed
commented
commented
mentioned
subscribed
mentioned
subscribed
commented
commented
mentioned
subscribed
head_ref_force_pushed
commented
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
commented
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
commented
commented
head_ref_force_pushed
commented
commented
mentioned
subscribed
head_ref_force_pushed
commented
commented
mentioned
subscribed
mentioned
subscribed
commented
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
mentioned
subscribed
line-commented
commented
mentioned
subscribed
commented
commented
commented
commented
head_ref_force_pushed
commented
head_ref_force_pushed
commented
commented
commented
commented
commented
commented
commented
commented
mentioned
subscribed
mentioned
subscribed
commented
cross-referenced
commented
commented
commented
commented
mentioned
subscribed
commented
mentioned
subscribed
commented
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xtuchyna/.local/share/virtualenvs/SrcOpsMetrics-Vwmk3Tpf/lib/python3.8/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/home/xtuchyna/.local/share/virtualenvs/SrcOpsMetrics-Vwmk3Tpf/lib/python3.8/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/home/xtuchyna/.local/share/virtualenvs/SrcOpsMetrics-Vwmk3Tpf/lib/python3.8/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/xtuchyna/.local/share/virtualenvs/SrcOpsMetrics-Vwmk3Tpf/lib/python3.8/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/home/xtuchyna/.local/share/virtualenvs/SrcOpsMetrics-Vwmk3Tpf/lib/python3.8/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 502 {"message": "Server Error"}
```

**Comment by s-t-e-v-e-n-k** [comment]
Is it always that one event? Is it after a certain number of events? Have you hit your rate limit? What happens if you skip that particular event?
