### ISSUE TITLE
GitHub 400 "Problems parsing JSON" when creating an issue

### ISSUE THREAD

**Issue by krmaxwell** [PyGithub/PyGithub#194]
I'm working from the `develop` branch and consistently get an `HTTP 400: Problems parsing JSON` when trying to create an issue.

The traceback, including the actual API call, is:

```
Traceback (most recent call last):
  File "import.py", line 68, in <module>
    issue=repo.create_issue(title=i['description'],body=comment,labels=ilabels)
  File "/home/kmaxwell/PyGithub/github/Repository.py", line 557, in create_issue
    post_parameters
  File "/home/kmaxwell/PyGithub/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, input))
  File "/home/kmaxwell/PyGithub/github/Requester.py", line 182, in __check
    raise self.__createException(status, output)
github.GithubException.GithubException: 400 {u'message': u'Problems parsing JSON'}
```

Additionally, I enabled console logging while debugging (per the contribution guidelines) and have the following logs:

```
POST https://api.github.com/repos/vz-risk/VCDB/issues {'Content-Type': 'application/json', 'Authorization': 'token (oauth token removed)', 'User-Agent': 'PyGithub/Python'} {"body": "http://www.heraldonline.com/2013/08/27/5152564/advanced-data-processing-inc-notification.html\n\nAnother of the ADP Partner breaches  There are several more on the pinboard--search term is ADP.\n\nhttp://posttrib.suntimes.com/news/porter/22190511-418/valpo-ambulance-users-could-have-had-personal-information-stolen.html\n\nhttp://www.healthdatamanagement.com/news/breach-notification-hipaa-privacy-security-46520-1.html\n\n\n2013 DataBreach NC", "labels": ["Breach"], "title": "VALPARAISO, Ind., Aug. 27, 2013: Advanced Data Processing, Inc.: Notification of Possible Unauthorized Access of Patient Information | PRNewswire | Rock Hill Herald Online"} ==> 400 {'status': '400 Bad Request', 'x-ratelimit-remaining': '4993', 'x-github-media-type': 'github.beta; format=json', 'x-content-type-options': 'nosniff', 'access-control-expose-headers': 'ETag, Link, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes', 'x-github-request-id': '54c3445d-e229-4b45-b3f1-ef528f1325be', 'x-accepted-oauth-scopes': 'repo, public_repo', 'content-length': '35', 'server': 'GitHub.com', 'x-ratelimit-limit': '5000', 'access-control-allow-credentials': 'true', 'date': 'Wed, 04 Sep 2013 03:27:33 GMT', 'access-control-allow-origin': '*', 'content-type': 'application/json; charset=utf-8', 'x-oauth-scopes': 'user, public_repo, repo, gist', 'x-ratelimit-reset': '1378268851'} {"message":"Problems parsing JSON"}
```

**Comment by matthewsimons-wf** [comment]
The body just had unescaped newline characters, a no-no for json.

`body.replace('\n', '\\n')`

I've also gotten 400s back from Github when a path wasn't urlquoted.
