### ISSUE TITLE
deleting files gives me 404 error

### ISSUE THREAD

**Issue by anim-e** [PyGithub/PyGithub#1949]
When I try to delete a file in my repository I get 404 error. the file exists in the repository tho so I am confused. Below is my code and bellow that is my full traceback. 
```python
contents = repo.get_contents('a1.html', ref='master')
print(contents.path)
repo.delete_file(contents.path, 'remove test', contents.sha, branch='master')
```
```
a1.html
Traceback (most recent call last):
  File "c:\Users\Yurishizu\Documents\GitHub\Chadley-bot\test\testing_github.py", line 14, in <module>
    repo.delete_file(contents.path, 'remove test', contents.sha, branch='master')
  File "C:\Users\Yurishizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\github\Repository.py", line 2212, in delete_file      
    headers, data = self._requester.requestJsonAndCheck(
  File "C:\Users\Yurishizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\github\Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "C:\Users\Yurishizu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\github\Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#delete-a-file"}
PS C:\Users\Yurishizu\Documents\GitHub\Chadley-bot> 
```

**Comment by anim-e** [comment]
I realised that if i use my access token to login instead of username and password it works.
