### ISSUE TITLE
Throwing Error if I compile my code with Pyinstaller

### ISSUE THREAD

**Issue by LoNE-W0LvES** [PyGithub/PyGithub#2035]
I made a script and it works perfectly but when I compile it with pyinstaller

`pyinstaller --onefile --icon='icon.ico' dmi.py`

It throws error, but if I don't compile it works

The code which is throwing error:

``` lang-py
import PySimpleGUIQt as Sg
from github import Github
from urllib import parse

g = Github("ghp_**********************************")
img_data = (g.get_user().get_repo('python-files')).get_contents(
    parse.quote('create.ico'), ref="main").content.replace('\n', '').encode()

layout = [
    [Sg.Text('                                                     ')]
]
window = Sg.Window("Add Tags", layout, icon=img_data, resizable=False, finalize=True)
while True:
    event, values = window.read()
    if event == Sg.WINDOW_CLOSED:
        window.close()
        break
```
The code below works even after compiling:
``` lang-py
import base64
import PySimpleGUIQt as Sg
import requests
header = {"Authorization": "token ghp_*******************************",
          "Accept": "application/vnd.github.v4.raw"}
encoded = base64.b64encode((requests.get('https://raw.githubusercontent.com/WoLvES-2x0/python-files/main/create.ico', headers=header)).content)
layout = [
    [Sg.Text('                                                     ')]
]
window = Sg.Window("Add Tags", layout, icon=encoded, resizable=False, finalize=True)
while True:
    event, values = window.read()
    if event == Sg.WINDOW_CLOSED:
        window.close()
        break

```
although I can do this in other way but main issue I'll face without Pygithub is 

`Get file name of all files in a repo`
``` lang-py
g_f_name = [str(i).replace('ContentFile(path="', '').replace('")', '') for i in (g.get_user().get_repo('node-files')).get_contents('') if i]
```
And
`commit changes to repo`
``` lang-py
repo.update_file(repo.get_contents('tags.txt').path, "committing files", tags_string, repo.get_contents('tags.txt').sha, branch="main")
```
error Is
``` lang-py
C:\pythoncharm\pythonProject4\dist>dmi.exe
Traceback (most recent call last):
  File "dmi.py", line 2, in <module>
  File "C:\Users\WoLvES\AppData\Local\Temp\embedded.rtin1sym.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "github\__init__.py", line 56, in <module>
  File "C:\Users\WoLvES\AppData\Local\Temp\embedded.rtin1sym.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "github\MainClass.py", line 59, in <module>
  File "C:\Users\WoLvES\AppData\Local\Temp\embedded.rtin1sym.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "github\Event.py", line 32, in <module>
  File "C:\Users\WoLvES\AppData\Local\Temp\embedded.rtin1sym.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "github\NamedUser.py", line 44, in <module>
  File "C:\Users\WoLvES\AppData\Local\Temp\embedded.rtin1sym.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "github\Organization.py", line 50, in <module>
  File "C:\Users\WoLvES\AppData\Local\Temp\embedded.rtin1sym.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "github\Repository.py", line 125, in <module>
  File "C:\Users\WoLvES\AppData\Local\Temp\embedded.rtin1sym.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "github\PublicKey.py", line 34, in <module>
  File "C:\Users\WoLvES\AppData\Local\Temp\embedded.rtin1sym.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "nacl\public.py", line 17, in <module>
  File "C:\Users\WoLvES\AppData\Local\Temp\embedded.rtin1sym.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "nacl\bindings\__init__.py", line 17, in <module>
  File "C:\Users\WoLvES\AppData\Local\Temp\embedded.rtin1sym.zip\shibokensupport\__feature__.py", line 142, in _import
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "nacl\bindings\crypto_aead.py", line 18, in <module>
  File "C:\Users\WoLvES\AppData\Local\Temp\embedded.rtin1sym.zip\shibokensupport\__feature__.py", line 142, in _import
  File "C:\Users\WoLvES\AppData\Local\Temp\embedded.rtin1sym.zip\shibokensupport\__feature__.py", line 142, in _import
ModuleNotFoundError: No module named '_cffi_backend'
[33116] Failed to execute script 'dmi' due to unhandled exception!
```

**Comment by eric-wieser** [comment]
Presuambly the way forward here is for PyInstaller configuration to either be committed to the PyNaCl project, or to pyinstaller itself to special-case PyNaCl.
