### ISSUE TITLE
Webhook: github.GithubException.UnknownObjectException: 404

### ISSUE THREAD

**Issue by Bluscream** [PyGithub/PyGithub#2126]
Using https://pygithub.readthedocs.io/en/latest/examples/Webhook.html i get the following error:

```
S:\Projects\Python\github-bot\venv\Scripts\python.exe S:/Projects/Python/github-bot/main.py
Traceback (most recent call last):
  File "S:\Projects\Python\github-bot\main.py", line 73, in <module>
    create_webhook()
  File "S:\Projects\Python\github-bot\main.py", line 66, in create_webhook
    repo = g.get_repo("{owner}/{repo_name}".format(owner=OWNER, repo_name=REPO_NAME))
  File "S:\Projects\Python\github-bot\venv\lib\site-packages\github\MainClass.py", line 330, in get_repo
    headers, data = self.__requester.requestJsonAndCheck("GET", url)
  File "S:\Projects\Python\github-bot\venv\lib\site-packages\github\Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "S:\Projects\Python\github-bot\venv\lib\site-packages\github\Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-repository"}
```

**Comment by jaychandra86** [comment]
hey, did you fix this error? I'm getting the same error when updating a  file on my git repository.

**Comment by Bluscream** [comment]
I didn't. Sorry, i gave up

**Comment by spralja** [comment]
I hade the same issue:
* enabling the `write:web_hook` scope on the GitHub API token fixed the issue
