### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Luckets** [PyGithub/PyGithub#2129]
Hi. I run a script for delete and write an data. sometimes run normaly, but affter show this error in pygithub, the script no run again, i use python3 and lib pygithub.
I dont no if has a limit for create files per day in github. Somebody can help me. Thanks.

```
<github.MainClass.Github object at 0x00000090ECFA9820>
--------------------------------------------
AuthenticatedUser(login=None)
Traceback (most recent call last):
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ERPSEC\auto.py", line 33, in <module>
    login = user.login
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\github\AuthenticatedUser.py", line 231, in login
    self._completeIfNotSet(self._login)
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\github\GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\github\GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\github\GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\github\Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\github\Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\github\Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\github\Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\github\Requester.py", line 127, in getresponse
    r = verb(
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Sistemas\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None))
```

**Comment by Katozaaaa** [comment]
try this, I got the same error, it helped me:
https://github.com/VFrontDe/ESXi-Customizer-PS/issues/15#issuecomment-656938625

**Comment by EnricoMi** [comment]
This is down to github not being able to serve the current load of connections, this is unrelated to any limits. You could add retries, but if this never connects, then you should troubleshoot your internet connection (e.g. proxy settings: #2426).

You can configure retries via the `retry` argument:

```python
gh = Github(retry=10)
```

You can configure more complex retry logic as follows:

```python
from urllib3.util import Retry

gh = Github(retry=Retry(10))
```

See https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry for all available options.

**Comment by namanbansal102** [comment]
Good One Very Helpful..
