### ISSUE TITLE
fail to explore some very simple repositories like near/near-docusaurus-styles

### ISSUE THREAD

**Issue by puiseux** [PyGithub/PyGithub#2294]
Trying to execute those lines : 
```
from github import Github

gc = Github()
repos = gc.get_user(login='near').get_repos()
repo = repos[65]
print(repo)
open_pulls = repo.get_pulls(state='open')
print('open_pulls OK')
stats_commit_activity = repo.get_stats_commit_activity()
print('stats_commit_activity OK')
```
**The display is  :** 

```
Repository(full_name="near/near-docusaurus-styles")
open_pulls OK
```

And then, frozen screen, during a lot of time, (15 mn at least ...). 
If I'm patient enough, I obtain finally an answer talking about Exception and  recursivity...

**Comment by puiseux** [comment]
Here is the error Message :
```
Traceback (most recent call last):
  File "/Users/puiseux/GitHub/crypto/scripts/testthread.py", line 29, in testRepo
    sca = repo.get_stats_commit_activity()
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/github/Repository.py", line 2951, in get_stats_commit_activity
    headers, data = self._requester.requestJsonAndCheck(
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/github/Requester.py", line 572, in __requestRaw
    return self.__requestRaw(original_cnx, verb, url, requestHeaders, input)
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/github/Requester.py", line 572, in __requestRaw
    return self.__requestRaw(original_cnx, verb, url, requestHeaders, input)
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/github/Requester.py", line 572, in __requestRaw
    return self.__requestRaw(original_cnx, verb, url, requestHeaders, input)
  [Previous line repeated 968 more times]
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/http/client.py", line 339, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/http/client.py", line 238, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/email/parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/email/parser.py", line 56, in parse
    feedparser.feed(data)
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/email/feedparser.py", line 176, in feed
    self._call_parse()
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/email/feedparser.py", line 180, in _call_parse
    self._parse()
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/email/feedparser.py", line 295, in _parsegen
    if self._cur.get_content_maintype() == 'message':
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/email/message.py", line 594, in get_content_maintype
    ctype = self.get_content_type()
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/email/message.py", line 578, in get_content_type
    value = self.get('content-type', missing)
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/email/message.py", line 471, in get
    return self.policy.header_fetch_parse(k, v)
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/email/_policybase.py", line 316, in header_fetch_parse
    return self._sanitize_header(name, value)
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/email/_policybase.py", line 287, in _sanitize_header
    if _has_surrogates(value):
  File "/Users/puiseux/opt/miniconda3/lib/python3.9/email/utils.py", line 57, in _has_surrogates
    s.encode()
RecursionError: maximum recursion depth exceeded while calling a Python object

```

**Comment by nitr7gen** [comment]
```py
from github import Github
import time

start = time.time()
print(Github().get_user(login='near').get_repos()[65])
end  = time.time()
print(f"{(end-start).__round__()} s")
```

(same code as yours but only the used vars )

![image](https://user-images.githubusercontent.com/115389864/199763351-ec4bfe02-15b8-4989-b9e0-23f3c8274ca0.png)
@puiseux
