### ISSUE TITLE
getting AssertionError: unsupported encoding: none only on aws

### ISSUE THREAD

**Issue by MaxOrtGit** [PyGithub/PyGithub#2312]
when i try to get the decoded_content on my windows computer it runs fine, and it used to run fin on the server but ever sence i updated it i geth this error when calling decoded_content on my aws server:
Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/vct-predictions-bot-sfowNqXl-py3.8/lib/python3.8/site-packages/discord/client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "vctpb/main.py", line 214, in on_ready
    save_savedata_from_github()
  File "/home/ubuntu/VCT-Predictions-Bot/vctpb/vctpb/savedata.py", line 163, in save_savedata_from_github
    f.write(content.decoded_content)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/vct-predictions-bot-sfowNqXl-py3.8/lib/python3.8/site-packages/github/ContentFile.py", line 59, in decoded_content
    assert self.encoding == "base64", f"unsupported encoding: {self.encoding}"
AssertionError: unsupported encoding: none

**Comment by MaxOrtGit** [comment]
a soulution i found was putting 
`content._encoding.value = "base64"`
above content.decoded_content

**Comment by etorth** [comment]
This is very annoying, I use PyGithub to save diaries on github by a plugin: PyGithubDiary.
But when the diary text file gets larger this error always get triggered.

**Comment by etorth** [comment]
To my experience for small text files it never trigger, only big text files (~1MBytes) it triggers.

**Comment by etorth** [comment]
For those who has trouble with this problem, check a solution here:

https://github.com/etorth/PyGithubDiary/blob/8a24682f0f65007c2387f0a765049a2fc07c2f2d/python3/PyGithubDiary.py#L99
