### ISSUE TITLE
get_contents raises an obscure exception when asking for contents of something which is a directory

### ISSUE THREAD

**Issue by Julian** [PyGithub/PyGithub#2343]
```
⊙  venv/bin/python -c 'from github import Github; print(Github().get_repo("json-schema-org/JSON-Schema-Test-Suite").get_contents("tests/"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/julian/Development/bowtie/venv/lib/python3.11/site-packages/github/Repository.py", line 1854, in get_contents
    return github.ContentFile.ContentFile(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/julian/Development/bowtie/venv/lib/python3.11/site-packages/github/GithubObject.py", line 283, in __init__
    super().__init__(requester, headers, attributes, completed)
  File "/Users/julian/Development/bowtie/venv/lib/python3.11/site-packages/github/GithubObject.py", line 84, in __init__
    self._storeAndUseAttributes(headers, attributes)
  File "/Users/julian/Development/bowtie/venv/lib/python3.11/site-packages/github/GithubObject.py", line 96, in _storeAndUseAttributes
    self._useAttributes(attributes)
  File "/Users/julian/Development/bowtie/venv/lib/python3.11/site-packages/github/ContentFile.py", line 191, in _useAttributes
    if "content" in attributes:  # pragma no branch
       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

This is probably a duplicate of #1059 (which was autoclosed for staleness).

**Comment by NielsKorschinsky** [comment]
I can confirm this.
I also got such an error, however it might be because the dir did not exist.

**Comment by ChristopherJHart** [comment]
For future reference to others - this traceback only seems to appear if the filepath passed into `get_contents()` has a trailing backslash (`/`).

In other words, instead of calling the following:
```python
contents = github_repository.get_contents("foo/")
```
Call the following:
```python
contents = github_repository.get_contents("foo")
```
