### ISSUE TITLE
Bug Report, get_workflows relies on filename instead of workflow name

### ISSUE THREAD

**Issue by trent-abc** [PyGithub/PyGithub#2361]
Bug Report

When a workflow is created in the `.github/workflows` directory with a filename, this permanently the name by which the [get_workflow](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_workflow) api refers to it.  If the filename is changed and pushed upstream (i.e. changing the extension from yaml to yml) the get_workflow will not find the new filename, it will continue to look for "my_original_workflow.yaml".  The most frustrating part of this bug is that it's looking for the "filename" not the "name".  both the new filename as well as the workflow name (which can be retrieved from the [get_workflows](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.get_workflows) api ) result in a 404 not found error.

I think the api should query the workflow `name` as it suggests that it does in the documentation

Steps to reproduce:

Create a function, main.py
```
import os
from github import Github

def list_workflows(gh_pat=None):
    token = os.getenv("MY_GITHUB_TOKEN", default=gh_pat)
    g = Github(token)
    repo_name = "Organization/my_repo"
    workflows = g.get_repo(repo_name).get_workflows()
    workflow_list = []
    for workflow in workflows:
        workflow_list.append(workflow.name)
    return workflow_list

print(list_workflows())
```

Call it and get the expected result
```
['main', 'my_other_workflow']
```

Create a function, gatherer.py
```
import os
from github import Github

def gather(statuses=["completed"], conclusions=["success", "failure"]):
    token = os.getenv("MY_GITHUB_TOKEN")
    g = Github(token)
    #wf_name = "my_other_workflow.yaml"
    wf_name = "my_other_workflow"
    repo_name = "Organization/my_repo"
    logs = []

    runs = [
        r
        for r in g.get_repo(repo_name).get_workflow(wf_name).get_runs()
        if r.status in statuses
    ]
    return runs

print(gather())
```

Call it and get a 404
```
Traceback (most recent call last):
  File "/Users/me/gatherer.py", line 19, in <module>
    print(gather())
  File "/Users/me/gatherer.py", line 14, in gather
    for r in g.get_repo(repo_name).get_workflow(wf_name).get_runs()
  File "/Users/me/.conda/lib/python3.9/site-packages/github/Repository.py", line 3032, in get_workflow
    headers, data = self._requester.requestJsonAndCheck(
  File "/Users/me/.conda/lib/python3.9/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/Users/me/.conda/lib/python3.9/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/actions#get-a-workflow"}
```

**Comment by ahoneiser** [comment]
(docs)[https://docs.github.com/en/rest/actions/workflows#get-a-workflow] say:

> You can replace `workflow_id` with the workflow file name. For example, you could use `main.yaml`.

(Repository.py)[https://github.com/PyGithub/PyGithub/blob/7902351d4fa501dc108dbf3724e93831d922f582/github/Repository.py#L3190-L3196]'s params reflect this.

Guess this should rather be a (feedback request)[https://support.github.com/request]?

**Comment by trent-abc** [comment]
Again, the issue I have is not only that it doesn't use the "workflow name", but that if the filename is changed to "main.yml" from "main.yaml" it will not return a result for "main.yml".  The filename has changed but querying the new filename results in a 404, while the old filename, no longer present in the repository returns 200.

**Comment by ahoneiser** [comment]
sorry @trent-abc, can't reproduce ..

used this to test:

```python
import os
import sys

import click
from github import Github
from github.GithubException import UnknownObjectException


class GhClient:
    __client = None

    def __init__(self):
        token = os.getenv("GITHUB_TOKEN")

        if token:
            self.__client = Github(token)

        else:
            self.__client = Github()

    def get_workflows(self, repo):
        return self.__client.get_repo(repo).get_workflows()

    def get_workflow(self, repo, workflow):
        return self.__client.get_repo(repo).get_workflow(workflow)


@click.command()
@click.argument("org")
@click.argument("repo")
@click.argument("workflow")
def list_workflow(org, repo, workflow):
    client = GhClient()

    try:
        workflow = client.get_workflow(f"{org}/{repo}", workflow)
        print(f"{workflow.name} ({workflow.id}, {workflow.path})")

    except UnknownObjectException as err:
        status = err.status
        msg = err.data.get("message")

        print(f"{status}: {msg}", file=sys.stderr)


if __name__ == "__main__":
    list_workflow()
```

Works with a `workflow_id` or a path name, just as explained by the docs. When I rename a workflow, old id or path gets me a 404, except for when Workflow runs are still available, GitHub keeps the Workflow Data in this case, of course.

Can you provide a more specific example? Are you getting the 200 because you've got Workflow Runs kept that are associated with the old path / id? Is your code using a name or a non-existant path / id when the 404 is returned?
