### ISSUE TITLE
SSLEOFERROR on sending the same big asset second time

### ISSUE THREAD

**Issue by Felixoid** [PyGithub/PyGithub#2385]
Hello, it's the same error faced in https://github.com/PyGithub/PyGithub/discussions/2264

Here's the minimal reproducing case:

```
$ dd if=/dev/zero of=/tmp/asset bs=10M count=10                
10+0 records in
10+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 0,0326497 s, 3,2 GB/s
$ cat repro.py 
from getpass import getpass
from pathlib import Path

from github import Github
from github.GithubException import GithubException

gh = Github(getpass(), per_page=100)
release = gh.get_repo("Felixoid/ClickHouse").get_release("v22.9.2.7-stable")


def upload_asset(release, path):
    try:
        release.upload_asset(str(path))
    except GithubException as e:
        if e.data["message"] == "Validation Failed" and [
            True
            for err in e.data["errors"]
            if err["code"] == "already_exists"  # type: ignore
        ]:
            print("exception")


for i in range(15):
    upload_asset(release, Path("/tmp/asset"))
$ python repro.py 
Password:
 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1076, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.10/http/client.py", line 998, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='uploads.github.com', port=443): Max retries exceeded with url: /repos/Felixoid/ClickHouse/releases/86328273/assets?label=&name=asset (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2396)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/felixoid/Space/Felixoid/github/ClickHouse/clickhouse-repos-manager/repro.py", line 24, in <module>
    upload_asset(release, Path("/tmp/asset"))
  File "/home/felixoid/Space/Felixoid/github/ClickHouse/clickhouse-repos-manager/repro.py", line 13, in upload_asset
    release.upload_asset(str(path))
  File "/usr/lib/python3.10/site-packages/github/GitRelease.py", line 256, in upload_asset
    resp_headers, data = self._requester.requestBlobAndCheck(
  File "/usr/lib/python3.10/site-packages/github/Requester.py", line 370, in requestBlobAndCheck
    *self.requestBlob(
  File "/usr/lib/python3.10/site-packages/github/Requester.py", line 490, in requestBlob
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/lib/python3.10/site-packages/github/Requester.py", line 528, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/usr/lib/python3.10/site-packages/github/Requester.py", line 555, in __requestRaw
    response = cnx.getresponse()
  File "/usr/lib/python3.10/site-packages/github/Requester.py", line 127, in getresponse
    r = verb(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='uploads.github.com', port=443): Max retries exceeded with url: /repos/Felixoid/ClickHouse/releases/86328273/assets?label=&name=asset (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2396)')))
$ pacman -Q python-pygithub 
python-pygithub 1.57-1
```

**Comment by Felixoid** [comment]
Today I've dug a bit deeper, and that's what I've found about `gh-cli`, that doesn't fail.

When I've executed it with `mitmproxy` as HTTPS proxy, it succeeds because of additional request to the API in advance:

```
> SSL_CERT_FILE=~/.mitmproxy/mitmproxy-ca-cert.cer HTTPS_PROXY=192.168.2.197:8080 gh release -R Felixoid/ClickHouse upload v22.9.2.7-stable /tmp/asset2
asset under the same name already exists: [asset2]
```

![image](https://user-images.githubusercontent.com/3025537/208426769-218c0804-a68f-4f04-807f-f65e12893891.png)

It looks like a good workaround. Sadly, it requires additional requests spent.
