### ISSUE TITLE
401 unauthorized after upgrading to 1.58.0

### ISSUE THREAD

**Issue by parberge** [PyGithub/PyGithub#2431]
We use `GithubIntegration.get_access_token` to authenticate and after upgrading we now get this response:

```
github.GithubException.GithubException: 401 {"message": "'Expiration time' claim ('exp') must be a numeric value representing the future time at which the assertion expires", "documentation_url": "https://docs.github.com/rest"}
```

Reverting to 1.57 solves the issue.

**Comment by EnricoMi** [comment]
This has likely been introduced by #1986.

**Comment by EnricoMi** [comment]
@parberge are you using PyGitHub with `multiprocess`?

**Comment by parberge** [comment]
@EnricoMi No, but we have celery tasks, that in theory could run at the same time is that is the concern here.
Didn't had it running for long since it caused problems in production, but it was quick - So i guess right away. I hope that helps.

**Comment by EnricoMi** [comment]
A full traceback would be useful to understand this.

**Comment by parberge** [comment]
Trying to reproduce this. Will post traceback if I'm successful.

**Comment by parberge** [comment]
OK I did manage. It actually takes a bit of time for the problem to happen.

The stack trace:

```
Traceback (most recent call last):
  File "/opt/piston/java/tasks.py", line 78, in fetch_versions_from_github
    github = Github(settings.GITHUB_AUTHENTICATION.get_access_token(settings.GITHUB_INTEGRATION_ID).token)
  File "/usr/local/lib/python3.8/site-packages/github/GithubIntegration.py", line 129, in get_access_token
    headers, response = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 400, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 425, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 401 {"message": "'Expiration time' claim ('exp') must be a numeric value representing the future time at which the assertion expires", "documentation_url": "https://docs.github.com/rest"}
```

**Comment by EnricoMi** [comment]
I think I know what the issue is. Let me work something out.

**Comment by EnricoMi** [comment]
@parberge please test my fix:

    pip install git+https://github.com/enricomi/pygithub.git@fix-app-auth

**Comment by parberge** [comment]
@EnricoMi To reproduce this I need to use our staging environment. That environment doesn't have git.
Any chance it could be published to pypi to make testing it easier for me?

**Comment by EnricoMi** [comment]
You could do a checkout elsewhere, run

    python -m pip install --upgrade pip
    python setup.py sdist bdist_wheel

and use `dist/PyGithub-1.56.dev69+gd96557b9-py3-none-any.whl` to install PyGithub from a file instead from the git url.

**Comment by parberge** [comment]
It's like the universe stops me from testing this:

```
pygithub on ⎇ fix-app-auth [?] via 🐍 v3.10.8 (pygithub) ❯ python setup.py sdist bdist_wheel
Traceback (most recent call last):
  File "/home/parberge/.pyenv/versions/3.10.8/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/parberge/.pyenv/versions/3.10.8/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.exceptions import CommandError
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/pip/_internal/exceptions.py", line 10, in <module>
    from pip._vendor.six import iteritems
ModuleNotFoundError: No module named 'pip._vendor.six'
Traceback (most recent call last):
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/home/parberge/.pyenv/versions/3.10.8/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpl35ji38h', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/parberge/repos/pygithub/setup.py", line 48, in <module>
    setuptools.setup(
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/setuptools/dist.py", line 718, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/pkg_resources/__init__.py", line 780, in resolve
    dist = best[req.key] = env.best_match(
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/lib/python3.10/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/home/parberge/.local/share/virtualenvs/pygithub-wLOgXaVA/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpl35ji38h', '--quiet', 'setuptools_scm']' returned non-zero exit status 1.
``` 

Seems to be something with my setup though. Hopefully I will have time to spend on this soon.

**Comment by EnricoMi** [comment]
You might have to update `pip` first.

**Comment by parberge** [comment]
Now I'm fighting with the problem that pip doesn't find the local file when I specify it in `requirements.txt`. Have tried relative paths and full paths...

To add to complexity we're using containers and we use docker compose to set the build context etc. But yeah I really want to help with this. Will see if I have some time to continue on this a bit later.

**Comment by s-t-e-v-e-n-k** [comment]
```
% python3 -mvenv $(mktemp -d)
% cd /tmp/tmp.Tif1yJVXAu 
% echo "/home/steven/PyGithub/dist/PyGithub-1.58.1-py3-none-any.whl" > requirements.txt
% . bin/activate
% which pip
/tmp/tmp.Tif1yJVXAu/bin/pip
% pip install -r requirements.txt
Processing /home/steven/PyGithub/dist/PyGithub-1.58.1-py3-none-any.whl
...
```

**Comment by parberge** [comment]
@EnricoMi Still hitting this error with 1.58.2:

```
Traceback (most recent call last):
  File "/opt/piston/java/tasks.py", line 69, in fetch_versions_from_github
    github = Github(settings.GITHUB_AUTHENTICATION.get_access_token(settings.GITHUB_INTEGRATION_ID).token)
  File "/usr/local/lib/python3.10/site-packages/github/GithubIntegration.py", line 135, in get_access_token
    headers, response = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.10/site-packages/github/Requester.py", line 398, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.10/site-packages/github/Requester.py", line 423, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 401 {"message": "'Expiration time' claim ('exp') must be a numeric value representing the future time at which the assertion expires", "documentation_url": "https://docs.github.com/rest"}
```

**Comment by EnricoMi** [comment]
I can confirm this issue exists. It cannot be fixed as a hotfix, as it requires some rework. So it will be fixed with the next minor release.

**Comment by cvirtucio** [comment]
hi, just as a data point, we're running into this with [get_org_installation()](https://github.com/PyGithub/PyGithub/blob/v1.58.2/github/GithubIntegration.py#L175), as well. we know it [always uses a fresh token](https://github.com/PyGithub/PyGithub/blob/v1.58.2/github/GithubIntegration.py#L83), just like `get_access_token()` per [this PR](https://github.com/PyGithub/PyGithub/pull/2460), so we're not sure what's going on there.

**Comment by EnricoMi** [comment]
This will be fixed in #2528.

**Comment by cvirtucio** [comment]
just to confirm as we're implementing a workaround before #2528 is merged and released. the problem is that the integration object [creates and caches a JWT](https://github.com/PyGithub/PyGithub/blob/217d4241872f428963f7cd959cf5baeec370f698/github/GithubIntegration.py#L52) which [then gets used in the Authorization header](https://github.com/PyGithub/PyGithub/blob/master/github/Requester.py#L651) as the request to retrieved an installed app's metadata is sent out, and so it wouldn't matter whether the integration refreshes the token in [get_org_installation()](https://github.com/PyGithub/PyGithub/blob/v1.58.2/github/GithubIntegration.py#L175)? is this correct? if I'm not mistaken, creating a new `GithubIntegration` before each attempt to call `get_org_installation()` should fix this in the meantime, right?

**Comment by beliaev-maksim** [comment]
@cvirtucio that is what we use in our case

that puts more load on GH API, but the only solution

**Comment by homanp** [comment]
I'm seeing this issue as well. Does downgrading fix this?

**Comment by EnricoMi** [comment]
Please test #2528:

    pip install git+https://github.com/enricomi/pygithub.git@requester-auth-rework

**Comment by cvirtucio** [comment]
fix works for us, as well
