### ISSUE TITLE
got multiple values for keyword argument 'headers'

### ISSUE THREAD

**Issue by michie1** [PyGithub/PyGithub#244]
```
import PyGithub
g = PyGithub.BlockingBuilder().Login('login', 'password').Build()
u = g.get_authenticated_user()
```

```
Traceback (most recent call last):
  File "follow.py", line 3, in <module>
    u = g.get_authenticated_user()
  File "/usr/local/lib/python2.7/dist-packages/PyGithub-2.0.0_alpha.1-py2.7.egg/PyGithub/Blocking/Github.py", line 186, in get_authenticated_user
    r = self.Session._request("GET", url)
  File "/usr/local/lib/python2.7/dist-packages/PyGithub-2.0.0_alpha.1-py2.7.egg/PyGithub/Blocking/Session.py", line 88, in _request
    request = requests.Request(verb, url, params=urlArguments, data=data, headers=headers)
TypeError: __init__() got multiple values for keyword argument 'headers'
```

**Comment by jzelinskie** [comment]
v2 is dead, i'll reopen if you can reproduce on master
