### ISSUE TITLE
URL is none repos for private domain

### ISSUE THREAD

**Issue by anantzoid** [PyGithub/PyGithub#2470]
I'm trying to create a pull request to a repo in privately hosted github but it's not able to set the URL correctly:

```
g = Github(base_url="https://<private-github>.com/api/v3", login_or_token="<token>")
repo = g.get_repo("org/repo")
pr = repo.create_pull(title="Test PR", body="Test body", head="new", base="main")
```
Gives me the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/agupta968/miniconda3/envs/py38/lib/python3.8/site-packages/github/Repository.py", line 1400, in create_pull
    return self.__create_pull_1(*args, **kwds)
  File "/Users/agupta968/miniconda3/envs/py38/lib/python3.8/site-packages/github/Repository.py", line 1431, in __create_pull_1
    return self.__create_pull(
  File "/Users/agupta968/miniconda3/envs/py38/lib/python3.8/site-packages/github/Repository.py", line 1444, in __create_pull
    headers, data = self._requester.requestJsonAndCheck(
  File "/Users/agupta968/miniconda3/envs/py38/lib/python3.8/site-packages/github/Requester.py", line 401, in requestJsonAndCheck
    *self.requestJson(
  File "/Users/agupta968/miniconda3/envs/py38/lib/python3.8/site-packages/github/Requester.py", line 501, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/Users/agupta968/miniconda3/envs/py38/lib/python3.8/site-packages/github/Requester.py", line 566, in __requestEncode
    url = self.__makeAbsoluteUrl(url)
  File "/Users/agupta968/miniconda3/envs/py38/lib/python3.8/site-packages/github/Requester.py", line 640, in __makeAbsoluteUrl
    assert o.hostname in [
AssertionError: None
```

I checked the `self._url` value in `__makeAbsoluteUrl` function and it's set to `None/pulls`.

Any advise will be appreciated.

**Comment by EnricoMi** [comment]
Which version of pygithub are you using?

**Comment by anantzoid** [comment]
Hi @EnricoMi
I'm using the latest version v1.58.0

**Comment by EnricoMi** [comment]
Can you confirm this error also exists for v1.57?

**Comment by EnricoMi** [comment]
Are you sure the value that you use for `<private-github>` is a proper domain?
