### ISSUE TITLE
add_to_following and remove_from_following failing with 404

### ISSUE THREAD

**Issue by conor-f** [PyGithub/PyGithub#2574]
Having some issues with `add_to_following` and `remove_from_following` Reproducible sample:

```python
from github import Github

gc = Github("<token>")
uc = gc.get_user()

print("Me:")
print(uc)
print(uc.login)

adam = gc.get_user("adamtheturtle")
print("Adam:")
print(adam)

uc.add_to_following(adam)
```

```
$ python3 ex.py
Me:
AuthenticatedUser(login=None)
conor-f
Adam:
NamedUser(login="adamtheturtle")
Traceback (most recent call last):
  File "ex.py", line 14, in <module>
    uc.add_to_following(adam)
  File "/home/conor/.local/lib/python3.8/site-packages/github/AuthenticatedUser.py", line 397, in add_to_following
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/conor/.local/lib/python3.8/site-packages/github/Requester.py", line 398, in requestJsonAndCheck
    return self.__check(
  File "/home/conor/.local/lib/python3.8/site-packages/github/Requester.py", line 423, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/users#follow-a-user"}
```

Can follow up with any further input needed. Similar behavior for `remove_from_following`.

On python3.8 on Ubuntu 20.04

**Comment by EnricoMi** [comment]
Works just fine:

```python
gh = github.Github(token)
me = gh.get_user()
me.login
'EnricoMi'

conor = gh.get_user("conor-f")
conor.followers
10

me.add_to_following(conor)
gh.get_user("conor-f").followers
11

me.remove_from_following(conor)
gh.get_user("conor-f").followers
10
```

Have you set the `user:follow` scope for your token?

https://docs.github.com/en/rest/users/followers?apiVersion=2022-11-28#follow-a-user

**Comment by conor-f** [comment]
I had the scope set, but while I was there I decided to regenerate the token and for some reason it then started working?

Thanks for looking into this for me. Annoying that a simple token refresh made it work!
