### ISSUE TITLE
tests is broken on windows

### ISSUE THREAD

**Issue by trim21** [PyGithub/PyGithub#2587]
caused by https://github.com/PyGithub/PyGithub/pull/2145

```text
  Traceback (most recent call last):
    File "C:\Users\Trim21\scoop\apps\python310\3.10.11\lib\threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "C:\Users\Trim21\scoop\apps\python310\3.10.11\lib\threading.py", line 953, in run
      self._target(*self._args, **self._kwargs)
    File "C:\Users\Trim21\proj\PyGithub\.venv\lib\site-packages\httpretty\core.py", line 1097, in fill_filekind
      status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
    File "C:\Users\Trim21\proj\PyGithub\tests\Framework.py", line 220, in __request_callback
      self.__readNextRequest(
    File "C:\Users\Trim21\proj\PyGithub\tests\Framework.py", line 193, in __readNextRequest
      assert self.__protocol == readLine(self.__file)
  AssertionError: assert 'https' == 'Authenticate...estEmails.txt'
    - AuthenticatedUser.testEmails.txt
    + https

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
```

**Comment by trim21** [comment]
why it's not broken in linux...

**Comment by trim21** [comment]
realy nice, `tests/ReplayData/RequesterThrottled.testShouldDeferRequests.txt` is a symbolic link...

**Comment by EnricoMi** [comment]
*argh*, I hate Windows...
