### ISSUE TITLE
Error when setting `required_conversation_resolution`

### ISSUE THREAD

**Issue by terenho** [PyGithub/PyGithub#2714]
After setting `required_conversation_resolution=True` in `edit_protection`, one gets an error
```
     required_conversation_resolution is github.GitHubObject.NotSet
AsertionError: True
```

**Comment by EnricoMi** [comment]
The fix in #2715 is right, but I cannot see how that could have caused above issue. Can you please provide the full stack trace and used version?

**Comment by terenho** [comment]
My barebone code to demonstrate this error is
```
from github import (
    Auth,
    Github,
    GithubException,
)
import os
import sys


def main():
    try:
        auth = Auth.Token(os.environ.get("GITHUB_PAT"))
        git = Github(auth=auth)
    except GithubException:
        print("Github authentication error")
        sys.exit(1)

    try:
        repo = git.get_user("terenho").get_repo("PyGithub")
        branch = repo.get_branch("main")
    except GithubException:
        print("Github get repo or branch error")
        sys.exit(1)

    branch.edit_protection(
        strict=True,
        required_conversation_resolution=True,
    )


if __name__ == "__main__":
    main()
```

The PyGithub version is `1.59.1`
```
$ /usr/local/bin/pip3 show PyGithub
Name: PyGithub
Version: 1.59.1
Summary: Use the full Github API v3
Home-page: https://github.com/pygithub/pygithub
Author: Vincent Jacques
Author-email: vincent@vincent-jacques.net
License: 
Requires: deprecated, pyjwt, pynacl, requests
Required-by: 
```

The trace is as follows
```
$ python3 github_branch_protection.py 
Traceback (most recent call last):
  File "github_branch_protection.py", line 32, in <module>
    main()
  File "github_branch_protection.py", line 25, in main
    branch.edit_protection(
  File "/home/teho/.local/lib/python3.8/site-packages/github/Branch.py", line 196, in edit_protection
    assert (
AssertionError: True
```

**Comment by EnricoMi** [comment]
Alright, this issue has been partially fixed in the meanwhile, so your fix completes that. Thanks!
