### ISSUE TITLE
PullRequest.is_merged does not handle token expiration

### ISSUE THREAD

**Issue by jorge-delphix** [PyGithub/PyGithub#2760]
# Context

I am trying to build some automation using PyGithub and a Github App to authenticate to our organization.
The token I can get has an expiration of 1 hour.

The idea of my workflow is to do the following steps:
1. Get a token from Github App
2. Create pull request
3. Notify reviewers
4. Wait for PR to be merged with a flexible timeout to allow reviewers time to review.
5. Once PR is merged, do more steps

The problem arises in 4 if the timeout exceeds 1 hour.

# Problem

In the scenario above I noticed that even after the authentication token has expired, calling `pr.is_merged()` returns `False`.

Looking at the code the behavior I was seeing makes sense:
```
    def is_merged(self) -> bool:
        """
        :calls: `GET /repos/{owner}/{repo}/pulls/{number}/merge <https://docs.github.com/en/rest/reference/pulls>`_
        """
        status, headers, data = self._requester.requestJson("GET", f"{self.url}/merge")
        return status == 204
```
since the status of the request with expired token would be 401.

I see two issues with this:
1. False negatives - a PR could have been merged but `is_merged` returns False. 
2. Consumer is not notified in any way that their authentication has expired.

This also differs from other methods that I have been using like `pr.get_commits().get_page(0)` or `pr.get_labels().get_page(0)` which fail with the expected `github.BadCredentialsException` as soon as the token expires.

I also tested with a token that has no access to my organization, but in that case an expected 403 was raised which seems to be handled by `github.GithubRetry`.

# Steps to Reproduce

1. Create a Github Token on your account with `repo` access
2. Use token to create a client and get a pull request `pr`
3. Remove Github token from your account
4 . Run `pr.is_merged` .

For example:
```
import github
github_client = github.Github("<YOUR TOKEN>")

upstream_repo = github_client.get_repo("PyGithub/PyGithub")
pr = upstream_repo.get_pull(2757)
pr.is_merged()
False
pr.get_commits().get_page(0)
[Commit(sha="7569ac6c33e3682fa42ddf7aee1640198461a557"), Commit(sha="626a0435d063b12f9a9501a282e7371fe8783494")]
#
# Remove token from account
#
pr.is_merged()
False
pr.get_commits().get_page(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/github/PaginatedList.py", line 258, in get_page
    headers, data = self.__requester.requestJsonAndCheck(
  File ".../site-packages/github/Requester.py", line 442, in requestJsonAndCheck
    return self.__check(
  File ".../site-packages/github/Requester.py", line 487, in __check
    raise self.__createException(status, responseHeaders, data)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

**Comment by EnricoMi** [comment]
Excellent finding, I think all that is needed here is changing `requestJson` into `requestJsonAndCheck`. This issue might exist in many places.

**Comment by jorge-delphix** [comment]
I thought that could work too but then I saw the API returns 404 if branch has not been merged https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#check-if-a-pull-request-has-been-merged--status-codes and that would cause the `check` logic in `requestJsonAndCheck` to raise an `UnknownObjectException`.

**Comment by bauergeorg** [comment]
> Excellent finding, I think all that is needed here is changing `requestJson` into `requestJsonAndCheck`. This issue might exist in many places.

It's possible that my problem (https://github.com/PyGithub/PyGithub/issues/2759) caused by the same... The pull request (https://github.com/PyGithub/PyGithub/issues/2759) can be helpful, too.

**Comment by EnricoMi** [comment]
Well, any non 204 response may cause a false-negative response of any method that uses `requestJson` and checks for `status == 204`, may it be an eventual-consitency 404 or a authentication issue.

**Comment by EnricoMi** [comment]
@jorge-delphix how do you create the Github App token in the first place? There might be some help to avoid the `BadCredentialsException` all together.

**Comment by jorge-delphix** [comment]
The code I was working on runs on Jenkins so we generate the Github App token via the github-branch-source-plugin. The expiration the plugin sets for the token is 1 hour, so that's why I was hitting this scenario in longer than 1 hour workfows.

**Comment by EnricoMi** [comment]
Using the `AppAuthenticationAuth`, the token would be refreshed for you, but this obviously requires the private key and installation_id: https://pygithub.readthedocs.io/en/stable/examples/Authentication.html#app-installation-authentication

**Comment by jorge-delphix** [comment]
Ah yeah that would work and that covers the scenario that I needed it for. I essentially wanted the error to be raised so I could implement the token refresh on my side. Good to know I could do it via pygithub instead.

**Comment by EnricoMi** [comment]
I'll keep this issue open for the general issue of `status == 204`.

**Comment by zain-asif-dev** [comment]
Opened a fix: https://github.com/PyGithub/PyGithub/pull/3542

Added a `checkStatusOrRaise` helper on `Requester` and switched every method using the `status == 204` pattern over to it (turned out to be 34 spots, not just `is_merged`). It treats 204 as True, 404 as False, and raises for anything else instead of silently returning False. Kept `create_dispatch`'s `throw=False` behavior untouched since that flag already exists for callers who want the old swallow-everything behavior.

While running the test suite I found a few existing tests whose recorded fixtures actually hit 403/422 responses that were being masked as False, so I updated those to expect the exception instead.
