### ISSUE TITLE
2.1.0 release fails on import with urllib3 1.25.8

### ISSUE THREAD

**Issue by patrick-rivos** [PyGithub/PyGithub#2773]
This was changed with https://github.com/urllib3/urllib3/commit/382ab32f23795c44faae83b4e8b18a16fb605a0a

Requiring urllib3 >= [1.26.0](https://github.com/urllib3/urllib3/releases/tag/1.26.0) should resolve this issue.

```
Collecting pygithub
  Obtaining dependency information for pygithub from https://files.pythonhosted.org/packages/d1/fe/fef8795433b3d0752b3fb764a833574b49aa49fce0ed1cd3e10150c5ac25/PyGithub-2.1.0.post0-py3-none-any.whl.metadata
  Downloading PyGithub-2.1.0.post0-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.22.0)
Collecting pynacl>=1.4.0 (from pygithub)
  Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 856.7/856.7 kB 22.8 MB/s eta 0:00:00
Collecting python-dateutil (from pygithub)
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 51.4 MB/s eta 0:00:00
Collecting pyjwt[crypto]>=2.4.0 (from pygithub)
  Obtaining dependency information for pyjwt[crypto]>=2.4.0 from https://files.pythonhosted.org/packages/2b/4f/e04a8067c7c96c364cef7ef73906504e2f40d690811c021e1a1901473a19/PyJWT-2.8.0-py3-none-any.whl.metadata
  Downloading PyJWT-2.8.0-py3-none-any.whl.metadata (4.2 kB)
Collecting typing-extensions>=4.0.0 (from pygithub)
  Obtaining dependency information for typing-extensions>=4.0.0 from https://files.pythonhosted.org/packages/24/21/7d397a4b7934ff4028987914ac1044d3b7d52712f30e2ac7a2ae5bc86dd0/typing_extensions-4.8.0-py3-none-any.whl.metadata
  Downloading typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from pygithub) (1.25.8)
Collecting Deprecated (from pygithub)
  Obtaining dependency information for Deprecated from https://files.pythonhosted.org/packages/20/8d/778b7d51b981a96554f29136cd59ca7880bf58094338085bcf2a979a0e6a/Deprecated-1.2.14-py2.py3-none-any.whl.metadata
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: cryptography>=3.4.0 in /home/runner/.local/lib/python3.8/site-packages (from pyjwt[crypto]>=2.4.0->pygithub) (41.0.4)
Requirement already satisfied: cffi>=1.4.1 in /home/runner/.local/lib/python3.8/site-packages (from pynacl>=1.4.0->pygithub) (1.16.0)
Collecting wrapt<2,>=1.10 (from Deprecated->pygithub)
  Downloading wrapt-1.15.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.5/81.5 kB 13.8 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->pygithub) (1.14.0)
Requirement already satisfied: pycparser in /home/runner/.local/lib/python3.8/site-packages (from cffi>=1.4.1->pynacl>=1.4.0->pygithub) (2.21)
Downloading PyGithub-2.1.0.post0-py3-none-any.whl (302 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 303.0/303.0 kB 62.4 MB/s eta 0:00:00
Downloading typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Downloading PyJWT-2.8.0-py3-none-any.whl (22 kB)
Installing collected packages: wrapt, typing-extensions, python-dateutil, pyjwt, pynacl, Deprecated, pygithub
Successfully installed Deprecated-1.2.14 pygithub-2.1.0.post0 pyjwt-2.8.0 pynacl-1.5.0 python-dateutil-2.8.2 typing-extensions-4.8.0 wrapt-1.15.0
Traceback (most recent call last):
  File "./scripts/download_artifact.py", line 4, in <module>
    from github import Auth, Github
  File "/home/runner/.local/lib/python3.8/site-packages/github/__init__.py", line 57, in <module>
    from .MainClass import Github
  File "/home/runner/.local/lib/python3.8/site-packages/github/MainClass.py", line 105, in <module>
    class Github:
  File "/home/runner/.local/lib/python3.8/site-packages/github/MainClass.py", line 112, in Github
    default_retry = GithubRetry()
  File "/home/runner/.local/lib/python3.8/site-packages/github/GithubRetry.py", line 74, in __init__
    kwargs["allowed_methods"] = kwargs.get("allowed_methods", Retry.DEFAULT_ALLOWED_METHODS.union({"GET", "POST"}))
AttributeError: type object 'Retry' has no attribute 'DEFAULT_ALLOWED_METHODS'
```

**Comment by EnricoMi** [comment]
Fix released, thanks!
