### ISSUE TITLE
`from github import Github` fails in new release 

### ISSUE THREAD

**Issue by goliaro** [PyGithub/PyGithub#2775]
As the title says. Here is the traceback:
```python
Traceback (most recent call last):
  File ".github/workflows/helpers/gpu_ci_helper.py", line 3, in <module>
    from github import Github
  File "/home/runner/.local/lib/python3.8/site-packages/github/__init__.py", line 57, in <module>
    from .MainClass import Github
  File "/home/runner/.local/lib/python3.8/site-packages/github/MainClass.py", line 105, in <module>
    class Github:
  File "/home/runner/.local/lib/python3.8/site-packages/github/MainClass.py", line 112, in Github
    default_retry = GithubRetry()
  File "/home/runner/.local/lib/python3.8/site-packages/github/GithubRetry.py", line 74, in __init__
    kwargs["allowed_methods"] = kwargs.get("allowed_methods", Retry.DEFAULT_ALLOWED_METHODS.union({"GET", "POST"}))
AttributeError: type object 'Retry' has no attribute 'DEFAULT_ALLOWED_METHODS'
```

**Comment by EnricoMi** [comment]
duplicates #2773
