### ISSUE TITLE
App authentication doesn't work

### ISSUE THREAD

**Issue by yalef** [PyGithub/PyGithub#2853]
I'm trying to authenticate like it's done in documentation: https://pygithub.readthedocs.io/en/latest/examples/Authentication.html#app-authentication

```python
app_id = "000000"
app_secret = open("privatekey.pem").read()

username = "username"
reponame = "reponame"

auth = github.Auth.AppAuth(app_id, app_secret)
gi = github.GithubIntegration(auth=auth)
installation_id = gi.get_repo_installation(username, reponame)
access_token = gi.get_access_token(installation_id)
github_client = github.Github(access_token)
```

But I got error:
```
Traceback (most recent call last):
  File "/home/yalef/Projects/git-settings-app/settings_app/test_git.py", line 12, in <module>
    installation_id = gi.get_repo_installation(username, reponame)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yalef/Projects/git-settings-app/.venv/lib/python3.11/site-packages/github/GithubIntegration.py", line 244, in get_repo_installation
    return self._get_installed_app(url=f"/repos/{owner}/{repo}/installation")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yalef/Projects/git-settings-app/.venv/lib/python3.11/site-packages/github/GithubIntegration.py", line 166, in _get_installed_app
    headers, response = self.__requester.requestJsonAndCheck("GET", url, headers=self._get_headers())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yalef/Projects/git-settings-app/.venv/lib/python3.11/site-packages/github/Requester.py", line 494, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yalef/Projects/git-settings-app/.venv/lib/python3.11/site-packages/github/Requester.py", line 525, in __check
    raise self.createException(status, responseHeaders, data)
github.GithubException.GithubException: 401 {"message": "'Issued at' claim ('iat') must be an Integer representing the time that the assertion was issued", "documentation_url": "https://docs.github.com/rest"}

```

Am I doing something wrong?

**Comment by EnricoMi** [comment]
Your code looks good. Is your local time set correctly?

**Comment by yalef** [comment]
Thank you! Looks like local time was wrong
