### ISSUE TITLE
squash_merge_commit_message settings do not work any longer

### ISSUE THREAD

**Issue by darkpandarts** [PyGithub/PyGithub#2890]
Hi,

I think  the `squash_merge_commit_message` Github api has changed. If I run the following code:

```
        ghub = Github(self.token)
        repo = ghub.get_repo(f"{self.owner}/{self.repository}")
        print(f"Repository: {repo.full_name}")
        # print(dir(repo))
        repo.edit(
            allow_squash_merge=True,
            squash_merge_commit_message="COMMIT_MESSAGES",
        )
```

I get the following error:

```
Traceback (most recent call last):
  File "/media/bsgt/jogi1/XX_local_PSYNC_linux2/XXX_CONTRACTING/stablecaps/0000_STABLECAPS_GITREPOS/scriptomatix/git/modify_github_settings/mod_github_settings.py", line 87, in <module>
    mgs.main()
  File "/media/bsgt/jogi1/XX_local_PSYNC_linux2/XXX_CONTRACTING/stablecaps/0000_STABLECAPS_GITREPOS/scriptomatix/git/modify_github_settings/mod_github_settings.py", line 33, in main
    repo.edit(
  File "/media/bsgt/jogi1/XX_local_PSYNC_linux2/XXX_CONTRACTING/stablecaps/0000_STABLECAPS_GITREPOS/scriptomatix/git/modify_github_settings/venv/lib/python3.9/site-packages/github/Repository.py", line 1949, in edit
    headers, data = self._requester.requestJsonAndCheck("PATCH", self.url, input=post_parameters)
  File "/media/bsgt/jogi1/XX_local_PSYNC_linux2/XXX_CONTRACTING/stablecaps/0000_STABLECAPS_GITREPOS/scriptomatix/git/modify_github_settings/venv/lib/python3.9/site-packages/github/Requester.py", line 537, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/media/bsgt/jogi1/XX_local_PSYNC_linux2/XXX_CONTRACTING/stablecaps/0000_STABLECAPS_GITREPOS/scriptomatix/git/modify_github_settings/venv/lib/python3.9/site-packages/github/Requester.py", line 598, in __check
    raise self.createException(status, responseHeaders, data)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"message": "Sorry, invalid setting combination. The following are valid combinations for the squash commit title and message: PR_TITLE and PR_BODY, PR_TITLE and BLANK, PR_TITLE and COMMIT_MESSAGES, COMMIT_OR_PR_TITLE and COMMIT_MESSAGES. (invalid_squash_commit_setting_combo)", "resource": "Repository", "field": "merge_commit_allowed", "code": "invalid"}], "documentation_url": "https://docs.github.com/rest/repos/repos#update-a-repository"}

```

The api options have changed as per the message:

```
The following are valid combinations for the squash commit title and message: PR_TITLE and PR_BODY, PR_TITLE and BLANK, PR_TITLE and COMMIT_MESSAGES, COMMIT_OR_PR_TITLE and COMMIT_MESSAGES.
``

Would it be possible to update the app to account for these new settings please? :)

**Comment by JackPGreen** [comment]
This is an undocumented behaviour of the GitHub API.

If you want to set the `squash_merge_commit_message ` property, you must also set the `squash_merge_commit_title` property to a validatable value **in the same request**, irrespective of the current value of `squash_merge_commit_title`
