### ISSUE TITLE
User Projects not showing up.

### ISSUE THREAD

**Issue by LorenzoCattai** [PyGithub/PyGithub#2967]
I am trying to access my github projects but they do not seem to exists according to PyGithub.

This is the code I'm trying to run (`GITHUB_TOKEN` censored):
```python
from github import Github

github = Github(GITHUB_TOKEN)

for repository in github.get_user().get_repos():
    print(repository.name)
    for project in repository.get_projects():
        print(project.name)
```
It only prints out the name of my repositories but not a single project name.

So I tried to get the project directly usign `github.get_project()` like this (`GITHUB_TOKEN` censored):
```python
from github import Github

github = Github(GITHUB_TOKEN)

project = github.get_project(1)
print(project.name)
```
But this errors out with:
```
Request GET /projects/1 failed with 403: Forbidden
Traceback (most recent call last):
  File "c:\Users\user\test\main.py", line 22, in <module>
    project = github.get_project(1)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\github\MainClass.py", line 464, in get_project
    headers, data = self.__requester.requestJsonAndCheck(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\github\Requester.py", line 548, in requestJsonAndCheck    
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\github\Requester.py", line 713, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\github\Requester.py", line 810, in __requestEncode        
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\github\Requester.py", line 844, in __requestRaw
    response = cnx.getresponse()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\github\Requester.py", line 196, in getresponse
    r = verb(
        ^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 938, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\github\GithubRetry.py", line 185, in increment
    raise Requester.createException(response.status, response.headers, content)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
github.GithubException.GithubException: 403 {"message": "Must have admin rights to Repository.", "documentation_url": "https://docs.github.com/rest/projects/projects#get-a-project"}
```

I have tried both code snippets with `classic` tokens and `fine grained tokens` (with all scopes enabled) from the repository and project owner user but the result is the same.

**Comment by LorenzoCattai** [comment]
This is most likely a duplicate of #2140, it should probably get renamed to just `projects` or `new projects` as I belive it's not in beta anymore if this new project type is what github created on my repositories by default.
