### ISSUE TITLE
Connection to Git repo failed

### ISSUE THREAD

**Issue by gauthamk89** [PyGithub/PyGithub#300]
Traceback (most recent call last):
  File "try-git.py", line 132, in <module>
    main()
  File "try-git.py", line 23, in create_repositories
    org = g.get_organization("My-organization")
  File "/usr/lib/python2.6/site-packages/github/MainClass.py", line 187, in get_organization
    "/orgs/" + login
  File "/usr/lib/python2.6/site-packages/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/lib/python2.6/site-packages/github/Requester.py", line 210, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/lib/python2.6/site-packages/github/Requester.py", line 247, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/lib/python2.6/site-packages/github/Requester.py", line 271, in __requestRaw
    requestHeaders
  File "/usr/lib64/python2.6/httplib.py", line 914, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 951, in _send_request
    self.endheaders()
  File "/usr/lib64/python2.6/httplib.py", line 908, in endheaders
    self._send_output()
  File "/usr/lib64/python2.6/httplib.py", line 780, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.6/httplib.py", line 739, in send
    self.connect()
  File "/usr/lib64/python2.6/httplib.py", line 1112, in connect
    sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/usr/lib64/python2.6/socket.py", line 567, in create_connection
    raise error, msg
socket.error: [Errno 111] Connection refused

**Comment by arpit1997** [comment]
This error is related to your individual machine although there are some reason possible for that

- most possible reason is that the port that this application is using is already in use by some other application. Maybe you can try a fresh reboot and try to run it again. Or check which port this appplicaton wants to use and free that port on your computer.

- another possible reason could be be that your are not connected to internet or you are using a proxy setting which pygithub can not resolve. 

hope that helps :+1:
