### ISSUE TITLE
Wrong exception type raised when requesting non-existent branch.

### ISSUE THREAD

**Issue by zhighleggett** [PyGithub/PyGithub#3011]
If requesting a branch that does not exist, a generic `GithubException` is raised, however the proper exception to be raised is `UnknownObjectException`. Per the docstring:

```
class UnknownObjectException(GithubException):
    """
    Exception raised when a non-existing object is requested (when Github API replies with a 404 HTML status)
    """
```

The reason this happens is because the code that generates the exception based on the HTTP error code is not only looking at the status, but is also looking at the message it encapsulates. It only builds the `UnknownObjectException` if the message is "not found" but the 404 HTTP response when requesting an unknown branch has the message "Branch not found".
```
      elif status == 404 and message == "not found":
            exc = GithubException.UnknownObjectException
```

Is there any reason that we are checking the contents of the message and not just the HTTP status code? If there is, would it at least be better to chang `message == "not found"` to `"not found" in message`?

Minimal example:
```
>>> import github
>>> gh = github.Github("ACCESS_TOKEN_REDACTED")
>>> org = gh.get_organization("ORG_NAME_REDACTED")
>>> repo = org.get_repo("REPO_NAME_REDACTED")
>>> branch = repo.get_branch("foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\zhighleggett\AppData\Local\Programs\Python\Python312\Lib\site-packages\github\Repository.py", line 2018, in get_branch
    headers, data = self._requester.requestJsonAndCheck("GET", f"{self.url}/branches/{branch}")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhighleggett\AppData\Local\Programs\Python\Python312\Lib\site-packages\github\Requester.py", line 548, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhighleggett\AppData\Local\Programs\Python\Python312\Lib\site-packages\github\Requester.py", line 609, in __check
    raise self.createException(status, responseHeaders, data)
github.GithubException.GithubException: 404 {"message": "Branch not found", "documentation_url": "https://docs.github.com/rest/branches/branches#get-a-branch", "status": "404"}
```

**Comment by EnricoMi** [comment]
The likely reason for this is the fact that Github likes to put different errors behind the same HTTP status code.

I agree, the message checking logic could be improved as suggested.

**Comment by zhighleggett** [comment]
Is there any reason to check the message at all? If the `UnknownObjectException` docstring is to be believed, any 404 error message should result in that exception.

**Comment by EnricoMi** [comment]
Fixed by #3299.
