### ISSUE TITLE
Repo.get_git_ref/create_git_ref inconsistent prefix

### ISSUE THREAD

**Issue by huwcbjones** [PyGithub/PyGithub#3014]
I've got a script that's creating a ref (branch) and replacing it if it already exists.

```py
branch_ref = "heads/my-ref"
with suppress(GithubException):
   repo.get_git_ref(branch_ref).delete()
ref =repo.create_git_ref(branch_ref, commit.sha)
``` 

By specifying the ref without the `refs/` prefix, I get the following:
```
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/$org/$repo/git/refs/heads/my-ref HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://api.github.com:443 "DELETE /repos/$org/$repo/git/refs/heads/my-ref HTTP/1.1" 204 0
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/$org/$repo/git/refs HTTP/1.1" 422 147
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    ref = repo.create_git_ref(branch_ref, commit.sha)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/github/Repository.py", line 1221, in create_git_ref
    headers, data = self._requester.requestJsonAndCheck("POST", f"{self.url}/git/refs", input=post_parameters)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pexbot/.local/lib/python3.11/site-packages/github/Requester.py", line 548, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/github/Requester.py", line 609, in __check
    raise self.createException(status, responseHeaders, data)
github.GithubException.GithubException: 422 {"message": "Reference name must start with 'refs/'.", "documentation_url": "https://docs.github.com/rest/git/refs#create-a-reference", "status": "422"}
```

If I specifying with the `refs/` prefix, I get the following:
```py
branch_ref = "refs/heads/my-ref"
with suppress(GithubException):
   repo.get_git_ref(branch_ref).delete()
ref =repo.create_git_ref(branch_ref, commit.sha)
``` 

```
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/$org/$repo/git/refs/refs/heads/my-ref HTTP/1.1" 404 None
DEBUG:urllib3.connectionpool:https://api.github.com:443 "POST /repos/$org/$repo/git/refs HTTP/1.1" 201 493
```

Note the double `refs/refs` in the GET request to check if the ref already exists.
I'm going to bodge around this, but it was wholy unexpected!

**Comment by EnricoMi** [comment]
I agree the double `refs` looks strange but I think that is correct. The first `refs` is part of the API, the second `refs` is part of the Git reference. This corresponds with Github and Git documentation.

It should read `branch_ref = "refs/heads/my-ref"`.

https://git-scm.com/book/en/v2/Git-Internals-Git-References
https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#create-a-reference

**Comment by huwcbjones** [comment]
I don't think it is correct, see these two API gets on PyGithub's master reference
```
huw: ~/D/PyGithub $ gh api 'repos/pexip/mee-charts/git/refs/refs/heads/master' | jq .
gh: Not Found (HTTP 404)
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/git/refs#get-all-references-in-a-namespace",
  "status": "404"
}
huw: ~/D/PyGithub $ gh api 'repos/pexip/mee-charts/git/refs/heads/master' | jq .
{
  "ref": "refs/heads/master",
  "node_id": "REF_kwDOMaA7F7FyZWZzL2hlYWRzL21hc3Rlcg",
  "url": "https://api.github.com/repos/pexip/mee-charts/git/refs/heads/master",
  "object": {
    "sha": "e9e85c16172a14085624d3689ab6068ce6f8c278",
    "type": "commit",
    "url": "https://api.github.com/repos/pexip/mee-charts/git/commits/e9e85c16172a14085624d3689ab6068ce6f8c278"
  }
}
```

What I expected was that the ref I passed to `create_ref` I could also pass to `get_ref`

**Comment by huwcbjones** [comment]
What I was expecting was to be able to pass the same ref to `create_ref` and then fetch it back with `get_ref`, but because `get_ref` appends a prefix of `refs/`, you cannot round trip.
And no, I do not believe the `refs/refs` is not part of the API, see below.
```
huw: ~/D/PyGithub $ gh api 'repos/PyGithub/PyGithub/git/refs/refs/heads/main' | jq .
gh: Not Found (HTTP 404)
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/git/refs#get-all-references-in-a-namespace",
  "status": "404"
}
huw: ~/D/PyGithub $ gh api 'repos/PyGithub/PyGithub/git/refs/heads/main' | jq .
{
  "ref": "refs/heads/main",
  "node_id": "MDM6UmVmMzU0NDQ5MDpyZWZzL2hlYWRzL21haW4=",
  "url": "https://api.github.com/repos/PyGithub/PyGithub/git/refs/heads/main",
  "object": {
    "sha": "23e8756397e9935e6a3307826de29c04cf853e94",
    "type": "commit",
    "url": "https://api.github.com/repos/PyGithub/PyGithub/git/commits/23e8756397e9935e6a3307826de29c04cf853e94"
  }
}
```

**Comment by EnricoMi** [comment]
As pointed out in #2992, it looks like `get_git_ref` false uses `git/refs` endpoint, where it should be `git/ref`, which requires the ref to be `refs/heads/main`.

**Comment by huwcbjones** [comment]
Oh that very much looks like I've come across the same bug!
Happy to close this off when that PR gets merged 😊
