### ISSUE TITLE
Error - ImportError: DLL load failed while importing _rust?

### ISSUE THREAD

**Issue by Rapid1898-code** [PyGithub/PyGithub#3085]
Hello - i try to run the below code :

```
from github import Github
from github import Auth
auth = Auth.Token("ghp_MyAPIKey")
g = Github(auth=auth)
```

but i get this error 

```
(test) C:\DEV\Python-Diverses\PyGitHub>python test1.py
Traceback (most recent call last):
  File "C:\DEV\Python-Diverses\PyGitHub\test1.py", line 1, in <module>
    from github import Github
  File "C:\DEV\.venv\test\lib\site-packages\github\__init__.py", line 53, in <module>
    from . import Auth
  File "C:\DEV\.venv\test\lib\site-packages\github\Auth.py", line 36, in <module>
    import jwt
  File "C:\DEV\.venv\test\lib\site-packages\jwt\__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "C:\DEV\.venv\test\lib\site-packages\jwt\api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "C:\DEV\.venv\test\lib\site-packages\jwt\algorithms.py", line 11, in <module>
  File "C:\DEV\.venv\test\lib\site-packages\jwt\__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "C:\DEV\.venv\test\lib\site-packages\jwt\api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "C:\DEV\.venv\test\lib\site-packages\jwt\__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "C:\DEV\.venv\test\lib\site-packages\jwt\api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "C:\DEV\.venv\test\lib\site-packages\jwt\__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "C:\DEV\.venv\test\lib\site-packages\jwt\api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "C:\DEV\.venv\test\lib\site-packages\jwt\__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "C:\DEV\.venv\test\lib\site-packages\jwt\api_jwk.py", line 7, in <module>
  File "C:\DEV\.venv\test\lib\site-packages\jwt\__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "C:\DEV\.venv\test\lib\site-packages\jwt\__init__.py", line 1, in <module>
  File "C:\DEV\.venv\test\lib\site-packages\jwt\__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "C:\DEV\.venv\test\lib\site-packages\jwt\api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "C:\DEV\.venv\test\lib\site-packages\jwt\algorithms.py", line 11, in <module>
    from .utils import (
  File "C:\DEV\.venv\test\lib\site-packages\jwt\utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "C:\DEV\.venv\test\lib\site-packages\cryptography\hazmat\primitives\asymmetric\ec.py", line 11, in <module>
    from cryptography.exceptions import UnsupportedAlgorithm, _Reasons
  File "C:\DEV\.venv\test\lib\site-packages\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: Die angegebene Prozedur wurde nicht gefunden.

(test) C:\DEV\Python-Diverses\PyGitHub>python test1.py
Traceback (most recent call last):
  File "C:\DEV\Python-Diverses\PyGitHub\test1.py", line 1, in <module>
    from github import Github
  File "C:\DEV\.venv\test\lib\site-packages\github\__init__.py", line 53, in <module>
    from . import Auth
  File "C:\DEV\.venv\test\lib\site-packages\github\Auth.py", line 36, in <module>
    import jwt
  File "C:\DEV\.venv\test\lib\site-packages\jwt\__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "C:\DEV\.venv\test\lib\site-packages\jwt\api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "C:\DEV\.venv\test\lib\site-packages\jwt\algorithms.py", line 11, in <module>
    from .utils import (
  File "C:\DEV\.venv\test\lib\site-packages\jwt\utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "C:\DEV\.venv\test\lib\site-packages\cryptography\hazmat\primitives\asymmetric\ec.py", line 11, in <module>
    from cryptography.exceptions import UnsupportedAlgorithm, _Reasons
  File "C:\DEV\.venv\test\lib\site-packages\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: Die angegebene Prozedur wurde nicht gefunden.
```

Why do i get this error?

**Comment by EnricoMi** [comment]
Looks like the `cryptography` package is not properly installed in your environment.

If you run `python -c "from cryptography.exceptions import UnsupportedAlgorithm"`, you should get the same `ImportError` exception, showing that this is unrelated  to PyGithub.

**Comment by Rapid1898-code** [comment]
ok thx - but how can i fix that?
(i tried to uninstall and install the cryptography package - but no change)

**Comment by Rapid1898-code** [comment]
i think i found the problem
it seems that this is not working with Python 3.9.0
but with Python 3.12.3 its working without problems
