### ISSUE TITLE
ImportError: No module named "request"

### ISSUE THREAD

**Issue by qlstudio** [PyGithub/PyGithub#376]
I am using Python 2.7.8. When I run `import github`, this happens:

    >>> import github

    Traceback (most recent call last):
      File "<pyshell#0>", line 1, in <module>
        import github
      File "C:\Python27\github\__init__.py", line 36, in <module>
        from .MainClass import Github
      File "C:\Python27\github\MainClass.py", line 28, in <module>
        import urllib.request, urllib.parse, urllib.error
    ImportError: No module named request

Did I install PyGithub incorrectly?

**Comment by qlstudio** [comment]
never mind, reinstalled and fixed
