### ISSUE TITLE
Bad format of due date in create milestone

### ISSUE THREAD

**Issue by zaibon** [PyGithub/PyGithub#396]
Format of date in create milstone doesn't follow github api. See YYYY-MM-DDTHH:MM:SSZ

test code
```
import datetime
import github

secret = '********'
api=github.Github(secret)
repo = api.get_repo("zaibon/temp")
repo.create_milestone(title="test", description="hello word", due_on=datetime.datetime.now())
```
Error
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    repo.create_milestone(title="test", description="hello word", due_on=datetime.datetime.now())
  File "/usr/local/lib/python3.5/dist-packages/github/Repository.py", line 954, in create_milestone
    input=post_parameters
  File "/usr/local/lib/python3.5/dist-packages/github/Requester.py", line 171, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/lib/python3.5/dist-packages/github/Requester.py", line 179, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {'message': 'Invalid request.\n\n2016-04-13 is not a valid date-time.', 'documentation_url': 'https://developer.github.com/v3/issues/milestones/#create-a-milestone'}
```

I have a fix in my forked repo.
https://github.com/zaibon/PyGithub/commit/8b0399c08286a0d4690d492a02f8b17cd2a24113
If it's good enough I can create a pull request.

**Comment by pnavarrc** [comment]
I found a workaround for this, create the milestone and then edit the milestone’s due date:

```python
# Create the milestone and set its due date
milestone = repo.create_milestone("title", description="description")
milestone.edit("title", due_on=datetime.datetime.now())
```

@zaibon solution looks good in my opinion, I am available to review and test if that helps.

**Comment by zaibon** [comment]
Thanks for the workaround, it help me to continue while waiting a proper fix.

I opened a PR for it at https://github.com/PyGithub/PyGithub/pull/397

**Comment by ultimate1352** [comment]
Hello :) I met the same problem.
Why this issue and PR are pending?
