### ISSUE TITLE
Getting redirected repo does not work if debug logging is enabled.

### ISSUE THREAD

**Issue by jpopelka** [PyGithub/PyGithub#470]
```
$ python3 -c "import github; token='...'; print(github.Github(token).get_repo('spumko/boom').raw_headers['status'])"

200 OK
```

```
python3 -c "import github, logging; logging.basicConfig(level=logging.DEBUG); token='...'; print(github.Github(token).get_repo('spumko/boom').raw_headers['status'])"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/github/GithubObject.py", line 105, in raw_headers
    self._completeIfNeeded()
  File "/usr/lib/python3.5/site-packages/github/GithubObject.py", line 252, in _completeIfNeeded
    self.__complete()
  File "/usr/lib/python3.5/site-packages/github/GithubObject.py", line 257, in __complete
    self._url.value
  File "/usr/lib/python3.5/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/lib/python3.5/site-packages/github/Requester.py", line 180, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {'documentation_url': 'https://developer.github.com/v3', 'message': 'Bad credentials'}
```

**Comment by scovetta** [comment]
This issue seems to exist in 1.53 -- using the same tests from from the top of the issue, getting 401 / "Bad Credentials" when logging is set to DEBUG.

It looks like this is happening here in Requester's __log function:
https://github.com/PyGithub/PyGithub/blob/master/github/Requester.py#L583
