### ISSUE TITLE
handling error when used Pagination

### ISSUE THREAD

**Issue by abbbbc** [PyGithub/PyGithub#514]
Hi,
I know i can use "PyGithub Error Handling" to handling error like this:
```
        try:
            self.g.get_user().create_key("Bad key", "xxx")
        except github.GithubException, exception:
            raised = True
```
But how to handling error when i used Pagination?
For example:
```
for repo in user.get_repos():
    print repo.name
```
I alway get `ssl.SSLError: The read operation timed out` in Pagination.
```
Traceback (most recent call last):
  File "getRepositories.py", line 230, in <module>
    GetRepos(o)
  File "getRepositories.py", line 28, in __init__
    self.getGithubOrganizationMembers()
  File "getRepositories.py", line 173, in getGithubOrganizationMembers
    self.getGithubMembersRepos(owner_login)
  File "getRepositories.py", line 179, in getGithubMembersRepos
    for repos in members_repos:
  File "/usr/local/lib/python2.7/dist-packages/github/PaginatedList.py", line 49, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python2.7/dist-packages/github/PaginatedList.py", line 61, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python2.7/dist-packages/github/PaginatedList.py", line 162, in _fetchNextPage
    headers=self.__headers
  File "/usr/local/lib/python2.7/dist-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/lib/python2.7/dist-packages/github/Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python2.7/dist-packages/github/Requester.py", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/usr/local/lib/python2.7/dist-packages/github/Requester.py", line 279, in __requestRaw
    response = cnx.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 400, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
ssl.SSLError: The read operation timed out
```

**Comment by 0x48piraj** [comment]
Same error.
```

pulls = repo.get_pulls(state='closed')
 for p in pulls:
```
