### ISSUE TITLE
Cannot get the access to Github API, getting 404 error while connecting.

### ISSUE THREAD

**Issue by hyadav5** [PyGithub/PyGithub#515]
Facing problem at the very first step, I know later calls might be smooth. Below is my code:

#--------------------------
from github import Github
g= Github("My github user login ID", "My github passwd", "http://github.com/OpenSCAP", 1000)
print( g.get_user().name)    #print None
print (g.get_repo("openscap").full_name)    #print None
print (g.get_repo("openscap").name)    #print None
for repo in g.get_user().get_repos():
	print (repo.name)    # Giving below traceback.
#---------------------------

Traceback (most recent call last):
  File "C:\MyDrive\SecureShield\GitHub\src\mygit.py", line 10, in <module>
    print (repo.name)
  File "C:\Python27\Lib\site-packages\github\Repository.py", line 435, in name
    self._completeIfNotSet(self._name)
  File "C:\Python27\Lib\site-packages\github\GithubObject.py", line 248, in _completeIfNotSet
    self._completeIfNeeded()
  File "C:\Python27\Lib\site-packages\github\GithubObject.py", line 252, in _completeIfNeeded
    self.__complete()
  File "C:\Python27\Lib\site-packages\github\GithubObject.py", line 257, in __complete
    self._url.value
  File "C:\Python27\Lib\site-packages\github\Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\Python27\Lib\site-packages\github\Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\Python27\Lib\site-packages\github\Requester.py", line 243, in __requestEncode
    url = self.__makeAbsoluteUrl(url)
  File "C:\Python27\Lib\site-packages\github\Requester.py", line 304, in __makeAbsoluteUrl
    if url.startswith("/"):
AttributeError: 'NoneType' object has no attribute 'startswith'

I know, I might be doing some wrong, but I have tried all the way and finally boiled down to this error. But unfortunetly got very less information on google. Any idea, what I am doind wrong. Have raised the issue over stackOverflow also.

http://stackoverflow.com/questions/41696232/not-able-to-instantiate-pygithub-modules-github-object

Thanks,
Hemant

**Comment by jayfk** [comment]
Your GitHub password has just been sent to ~62 people by mail. Please change it.

**Comment by kemsta** [comment]
change base_url to 'https://api.github.com' or delete him
