### ISSUE TITLE
Test recorder adds wrong string for token authorization

### ISSUE THREAD

**Issue by meneal** [PyGithub/PyGithub#516]
When recording a test and using a `GithubCredentials.py` like:

```
login = "meneal"
password = ""
oauth_token = "REDACTED"
```

the test recorder places the string `token private_token_removed` in the recorded file.  When the test is run after the recording is made, the following stack trace is produced:

```
Traceback (most recent call last):
  File "github/tests/OrganizationHasInMembers.py", line 32, in setUp
    self.user = self.g.get_user("meneal")
  File "github/MainClass.py", line 159, in get_user
    "/users/" + login
  File "github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "github/Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "github/Requester.py", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "github/Requester.py", line 277, in __requestRaw
    requestHeaders
  File "github/tests/Framework.py", line 151, in request
    self.__testCase.assertEqual(headers, eval(readLine(self.__file)))
AssertionError: {'Authorization': 'Basic login_and_password_removed', 'User-Agent': 'PyGithub/Py [truncated]... != {'Authorization': 'token private_token_removed', 'User-Agent': 'PyGithub/Python' [truncated]...
- {'Authorization': 'Basic login_and_password_removed',
+ {'Authorization': 'token private_token_removed',
   'User-Agent': 'PyGithub/Python'}
```

I manually changed the string in the recorded file to be `Basic login_and_password_removed` and the test passed with no error. I believe there are two options for this:

- Make the test in `Framework.py` in some way accept the `token_private_token_removed`
- Change something(not sure what this is offhand) in the recorder to make it use `Basic login_and_password_removed` regardless of whether a token or basic login is used.

**Comment by sfdye** [comment]
I have the same concern with you. With a lot of users turning on 2-factor authentication, we should support record test data with user token as well. Right now I have to manually replace all `token_private_token_removed` with `login_and_password_removed`.

**Comment by s-t-e-v-e-n-k** [comment]
I keep getting bitten by this, so I may get sufficiently annoyed to fix it.

**Comment by Diwasdrpm** [comment]
yes, I also get it same

**Comment by treee111** [comment]
I had that trouble as well.
For reference: One needs to replace the string **two times** in the recorded file - at upper and lower position.

**Comment by EnricoMi** [comment]
Is this still a problem? Unless you run `pytest --record` with `--auth_with_token`, it should prefer the login / basic auth method.

**Comment by treee111** [comment]
I only got it running with `--auth_with_token`, thought that is needed die to 2 factor authentication. Is this not correct and I could recors in another way?
