### ISSUE TITLE
Issues Connecting with Github Enterprise

### ISSUE THREAD

**Issue by swtch1** [PyGithub/PyGithub#546]
I am attempting to make a simple connection to my GitHub Enterprise instance but I keep getting a 502 error.  The setup is very simple so I'm a bit perplexed.  I've verified I can reach port 443 on the site address with Python socket.

`TOKEN = 'abc123'
g = Github(TOKEN, base_url='https://my.enterprise.github.com/api/v3
print(g.get_user().name)`

Resulting error:
`C:\Python27\python.exe "C:/project/testing.py"
Traceback (most recent call last):
  File "C:/project/testing.py", line 18, in <module>
    print(g.get_user().name)
  File "C:\Python27\lib\site-packages\github\AuthenticatedUser.py", line 221, in name
    self._completeIfNotSet(self._name)
  File "C:\Python27\lib\site-packages\github\GithubObject.py", line 251, in _completeIfNotSet
    self._completeIfNeeded()
  File "C:\Python27\lib\site-packages\github\GithubObject.py", line 255, in _completeIfNeeded
    self.__complete()
  File "C:\Python27\lib\site-packages\github\GithubObject.py", line 260, in __complete
    self._url.value
  File "C:\Python27\lib\site-packages\github\Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\Python27\lib\site-packages\github\Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\Python27\lib\site-packages\github\Requester.py", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\Python27\lib\site-packages\github\Requester.py", line 277, in __requestRaw
    requestHeaders
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 897, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 859, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "C:\Python27\lib\httplib.py", line 839, in connect
    self._tunnel()
  File "C:\Python27\lib\httplib.py", line 821, in _tunnel
    message.strip()))
socket.error: Tunnel connection failed: 502 Bad Gateway`

Python Version: 2.7.11 and 3.5.2
PyGithub Version: 1.33

**Comment by ctcreel** [comment]
https://stackoverflow.com/questions/21698009/github-api-502-error

**Comment by angelonakosge** [comment]
How did you end up solving your issue? Thx

**Comment by sfdye** [comment]
@swtch1 is this still an issue please?

**Comment by swtch1** [comment]
Retested and confirmed.  This is working correctly now.  Thank you for following up.
