### ISSUE TITLE
Error while trying to update a file using update_file()

### ISSUE THREAD

**Issue by vinayakvivek** [PyGithub/PyGithub#550]
error traceback :
```
Traceback (most recent call last):
  File "pygit-test.py", line 48, in <module>
    sha = sha, branch = 'master')
  File "<PROJECT_ROOT>/env/lib/python2.7/site-packages/github/Repository.py", line 1369, in update_file
    input=put_parameters
  File "<PROJECT_ROOT>/env/lib/python2.7/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "<PROJECT_ROOT>/env/lib/python2.7/site-packages/github/Requester.py", line 180, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Not Found'}
```

I ran the following code :

```python
sha = repo.get_contents('test').sha
repo.update_file(
	path = 'test', 
	message = 'Update test using GithubAPI', 
	content = base64.b64encode('updated test'), 
	committer=InputGitAuthor("vinayakvivek", email, "2016-01-15T16:13:30+12:00"),
	author=InputGitAuthor("vinayakvivek", email, "2016-01-15T16:13:30+12:00"),
	sha = sha, branch = 'master')
```

Any help would be highly appreciated :)

**Comment by vinayakvivek** [comment]
I think #545 is a similar issue.

**Comment by paulbovbel** [comment]
Seeing the same issue

**Comment by kevinjcash** [comment]
I am seeing this as well.

**Comment by kevinjcash** [comment]
I got past this, I just needed a leading slash in the path.

**Comment by shufanhao** [comment]
I also hit this issue

**Comment by shufanhao** [comment]
I also hit the same issue.

**Comment by shufanhao** [comment]
I find the root cause is that the role of your account must be admin role.
