### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by moghya** [PyGithub/PyGithub#559]
Traceback (most recent call last):
  File "C:/Users/moghya_s/Desktop/toGithub/test.py", line 11, in <module>
    test_upToGithub()
  File "C:/Users/moghya_s/Desktop/toGithub/test.py", line 8, in test_upToGithub
    user.cforceUpload('codeforcesUsername','codeforcesPassword')
  File "C:\Users\moghya_s\Desktop\toGithub\upload\uploader.py", line 45, in cforceUpload
    self.repo.create_file('/cforce/'+abc['contestId']+'/'+abc['problemName']+'/'+abc['id']+'.'+abc['ext'],'cforce solution for '+abc['problemName']+' with submissionId '+abc['id']+' is added.',abc['code'])
  File "C:\Program Files\Anaconda3\lib\site-packages\github\Repository.py", line 1310, in create_file
    input=put_parameters
  File "C:\Program Files\Anaconda3\lib\site-packages\github\Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\Program Files\Anaconda3\lib\site-packages\github\Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\Program Files\Anaconda3\lib\site-packages\github\Requester.py", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\Program Files\Anaconda3\lib\site-packages\github\Requester.py", line 283, in __requestRaw
    output = response.read()
  File "C:\Program Files\Anaconda3\lib\http\client.py", line 458, in read
    s = self.fp.read()
  File "C:\Program Files\Anaconda3\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\Anaconda3\lib\ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\Anaconda3\lib\ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "C:\Program Files\Anaconda3\lib\ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by moghya** [comment]
This was due to spaces in path string passed to create_file function

**Comment by moghya** [comment]
#567 look into this it solves problem.
