### ISSUE TITLE
Fork a repository into Github account 

### ISSUE THREAD

**Issue by sandipmgiri** [PyGithub/PyGithub#626]
I am trying to fork a repo using below code : 

```
from github import Github
g = Github("usr_name", "psw")
github_user = g.get_user()
repo = "https://github.com/gregof/abc"
myfork = github_user.create_fork(repo)
```

However I am getting following errors , looks like I am missing something. 
```
Traceback (most recent call last):
  File "f.py", line 5, in <module>
    myfork = github_user.create_fork(repo)
  File "/usr/lib/python2.7/dist-packages/github/AuthenticatedUser.py", line 446, in create_fork
    assert isinstance(repo, github.Repository.Repository), repo
AssertionError: https://github.com/gregof/abc

```
Please provide comments on this .Thanks!

**Comment by sfdye** [comment]
@sandipmgiri It's expecting a `Repository` object, not a string literal.

So this will work:
```
repo = g.get_repo('gregof/abc')
```
