### ISSUE TITLE
base_url private github or github enterprise 

### ISSUE THREAD

**Issue by Kravennagen** [PyGithub/PyGithub#646]
#Hi, I really don't understand why this code:
```
g = Github("privateAccount", "privatePass")

        for org in g.get_user().get_orgs():
            print(org.name)
```
works perfectly but when I want to get the same informations from my enterprise account it doesn't works:
```
g = Github("enterpriseAccount", "enterprisePass", base_url="https://enterprise-url-github")

        for org in g.get_user().get_orgs():
            print(org.name)
```
And I get this error:
```

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mflamant/Documents/bot/CiscoSparkPython/testbotforgithub/main.py", line 44, in Main
    bot.isRunnable()
  File "/home/mflamant/Documents/bot/CiscoSparkPython/testbotforgithub/utils/Compute.py", line 48, in isRunnable
    self.spark(message[0], message[1])
  File "/home/mflamant/Documents/bot/CiscoSparkPython/testbotforgithub/testbotforgithub.py", line 33, in spark
    return self.answer(details.roomId, markdown=self.gitTest(details))
  File "/home/mflamant/Documents/bot/CiscoSparkPython/testbotforgithub/testbotforgithub.py", line 48, in gitTest
    self.answer(details.roomId, markdown=org.name)
  File "/usr/local/lib/python2.7/dist-packages/PyGithub-1.35-py2.7.egg/github/Organization.py", line 191, in name
    self._completeIfNotSet(self._name)
  File "/usr/local/lib/python2.7/dist-packages/PyGithub-1.35-py2.7.egg/github/GithubObject.py", line 251, in _completeIfNotSet
    self._completeIfNeeded()
  File "/usr/local/lib/python2.7/dist-packages/PyGithub-1.35-py2.7.egg/github/GithubObject.py", line 255, in _completeIfNeeded
    self.__complete()
  File "/usr/local/lib/python2.7/dist-packages/PyGithub-1.35-py2.7.egg/github/GithubObject.py", line 260, in __complete
    self._url.value
  File "/usr/local/lib/python2.7/dist-packages/PyGithub-1.35-py2.7.egg/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/lib/python2.7/dist-packages/PyGithub-1.35-py2.7.egg/github/Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/usr/local/lib/python2.7/dist-packages/PyGithub-1.35-py2.7.egg/github/Requester.py", line 243, in __requestEncode
    url = self.__makeAbsoluteUrl(url)
  File "/usr/local/lib/python2.7/dist-packages/PyGithub-1.35-py2.7.egg/github/Requester.py", line 304, in __makeAbsoluteUrl
    if url.startswith("/"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
Have you any idea, I think it because of the base_url, but I have to use it if not I can't get my informations...

**Comment by Kravennagen** [comment]
Adding /api/v3 to the end of my URL and it works !
