### ISSUE TITLE
pygithub3 fails to install: ModuleNotFoundError: No module named 'github'

### ISSUE THREAD

**Issue by kristi** [PyGithub/PyGithub#665]
pygithub3 fails to install on Python 3.6.3

```
# mkvirtualenv test-pygithub3
# pip install pygithub3
Collecting pygithub3
  Using cached pygithub3-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kz/lxl7qsq55tsgctldpsfnvz4r0000gn/T/pip-build-pxv7mup6/pygithub3/setup.py", line 7, in <module>
        import pygithub3
      File "/private/var/folders/kz/lxl7qsq55tsgctldpsfnvz4r0000gn/T/pip-build-pxv7mup6/pygithub3/pygithub3/__init__.py", line 10, in <module>
        from github import Github
    ModuleNotFoundError: No module named 'github'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/kz/lxl7qsq55tsgctldpsfnvz4r0000gn/T/pip-build-pxv7mup6/pygithub3/
```

OSX 10.12.6
PyEnv 1.1.5
Python 3.6.3

**Comment by kristi** [comment]
Also fails on Python 3.3.6 and 3.5.4

**Comment by kristi** [comment]
Oh sorry, it's `pip install PyGithub`
