### ISSUE TITLE
SSL error using sample code

### ISSUE THREAD

**Issue by Squ1dd13** [PyGithub/PyGithub#742]
Using the sample code, when I run the code, i get 'ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'

**Comment by sfdye** [comment]
Could you please provide more details of the issue?

**Comment by meteozond** [comment]
@sfdye we've got the same issue with Python 3.6.4. What exact details are you interested in?

```python
from getpass import getpass

from github import Github
username = input("GitHub username: ")
password = getpass("GitHub password: ")

g = Github(username, password)

print(list(g.get_user().get_repos()))
```

```bash
python labels.py
```

```python
Traceback (most recent call last):
  File "labels.py", line 9, in <module>
    print(list(g.get_user().get_repos()))
  File "/Users/meteozond/.virtualenvs/pik/lib/python3.6/site-packages/github/PaginatedList.py", line 58, in __iter__
    newElements = self._grow()
  File "/Users/meteozond/.virtualenvs/pik/lib/python3.6/site-packages/github/PaginatedList.py", line 70, in _grow
    newElements = self._fetchNextPage()
  File "/Users/meteozond/.virtualenvs/pik/lib/python3.6/site-packages/github/PaginatedList.py", line 172, in _fetchNextPage
    headers=self.__headers
  File "/Users/meteozond/.virtualenvs/pik/lib/python3.6/site-packages/github/Requester.py", line 185, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/Users/meteozond/.virtualenvs/pik/lib/python3.6/site-packages/github/Requester.py", line 231, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/Users/meteozond/.virtualenvs/pik/lib/python3.6/site-packages/github/Requester.py", line 284, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/Users/meteozond/.virtualenvs/pik/lib/python3.6/site-packages/github/Requester.py", line 309, in __requestRaw
    requestHeaders
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

```

**Comment by meteozond** [comment]
Looks like I've found solution myself. It suppose to be python installation issue. 

If you are on macos, just run:

```bash
$ "/Applications/Python 3.6/Install Certificates.command"
```

**Comment by sfdye** [comment]
I am closing this.
