### ISSUE TITLE
repo.get_teams() + team.get_members() doesn't work

### ISSUE THREAD

**Issue by foolip** [PyGithub/PyGithub#756]
My script:
```Python
import sys

from github import Github


def main():
    token = '123456' # redacted
    g = Github(token)
    w3c_org = g.get_organization('w3c')
    wpt_org = g.get_organization('web-platform-tests')
    wpt_repo = w3c_org.get_repo('web-platform-tests')

    invited_users = set(wpt_org.get_members())

    all_users = set(wpt_repo.get_collaborators())

    # wpt_repo.get_teams() + team.members() doesn't work, but
    # w3c_org.get_teams() + team.members() does, so use the first
    # just to filter the second. Sigh?
    wpt_team_ids = set(team.id for team in wpt_repo.get_teams())
    for team in w3c_org.get_teams():
        if team.id not in wpt_team_ids:
            continue
        print(team)
        for user in team.get_members():
            if user in all_users:
                continue
            print('User {} is team member, not repo collaborator'.format(user.login))
            all_users.add(user)


if __name__ == '__main__':
    main()
```

The "sight" comment is where there seems to be a bug. Iterating over wpt_repo.get_teams() directly yields the same 4 teams as this loop, but `team.get_members()` then fails like this:
```
Traceback (most recent call last):
  File "invite.py", line 40, in <module>
    main()
  File "invite.py", line 25, in main
    for user in team.get_members():
  File "/usr/local/google/home/foolip/src/bikeshed-tests/env/lib/python3.5/site-packages/github/PaginatedList.py", line 58, in __iter__
    newElements = self._grow()
  File "/usr/local/google/home/foolip/src/bikeshed-tests/env/lib/python3.5/site-packages/github/PaginatedList.py", line 70, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/google/home/foolip/src/bikeshed-tests/env/lib/python3.5/site-packages/github/PaginatedList.py", line 172, in _fetchNextPage
    headers=self.__headers
  File "/usr/local/google/home/foolip/src/bikeshed-tests/env/lib/python3.5/site-packages/github/Requester.py", line 185, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/local/google/home/foolip/src/bikeshed-tests/env/lib/python3.5/site-packages/github/Requester.py", line 198, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {'documentation_url': 'https://developer.github.com/v3/teams/members/#list-team-members', 'message': 'Not Found'}
```

**Comment by sfdye** [comment]
Sorry I don't have access to your org so I couldn't see what's wrong. But I just tried for my org and all the above methods worked. If it returns 404 then something genuinely does not exist. 

It will be helpful it you can provide more context.

**Comment by foolip** [comment]
What kind of debugging can I enable to make this possible to diagnose?

**Comment by sfdye** [comment]
Perhaps you can send a raw HTTP requests and see the response?
Like `GET /repos/:owner/:repo/teams`

https://developer.github.com/v3/repos/#list-teams

If raw requests returns you the same 404, then it's not a PyGithub issue anymore.

**Comment by sfdye** [comment]
Closing this for now. Feel free to re-open if still an issue.
