### ISSUE TITLE
GitReleaseAsset.uploader AttributError

### ISSUE THREAD

**Issue by sarum9in** [PyGithub/PyGithub#778]
Affected version: 1.39.
Tested in multiple repositories, example below.

```python
list(github.Github().get_organization('mesonbuild').get_repo('meson').get_release('0.46.0').get_assets())[0].uploader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/github/GitReleaseAsset.py", line 149, in uploader
    return self._uploader.value
AttributeError: 'NamedUser' object has no attribute 'value'
```

**Comment by sfdye** [comment]
@sarum9in Thanks for reporting! Fixed now, will include it in the next release.
