### ISSUE TITLE
Two Factor: How Do I Use It?

### ISSUE THREAD

**Issue by grayaii** [PyGithub/PyGithub#781]
I have MFA enabled for my account.

g = Github("my_email", "my_password")
org = g.get_organization('my_org')
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/foo/.virtualenvs/skippy/lib/python3.4/site-packages/github/MainClass.py", line 198, in get_organization
    "/orgs/" + login
  File "/Users/foo/.virtualenvs/skippy/lib/python3.4/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/Users/foo/.virtualenvs/skippy/lib/python3.4/site-packages/github/Requester.py", line 180, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.TwoFactorException: 401 {'documentation_url': 'https://developer.github.com/v3/auth#working-with-two-factor-authentication', 'message': 'Must specify two-factor authentication OTP code.'}
```

I have my phone with my 6 digits rotating number, but where do I put it?
Sorry for the silly question, but I'm just getting my feet wet with Two Factor Authentication.

**Comment by grayaii** [comment]
OMG! Duh. I figured it out. lol.
In github, go to settings, then Developer Settings, then Personal Access Tokens.
Once generated, I can:
g = Github("token")
org = g.get_organization('my_org')
