### ISSUE TITLE
Timeout exception in request for Issues (created and closed) from a Repository 

### ISSUE THREAD

**Issue by jpmartins201** [PyGithub/PyGithub#808]
Trying to receive the number of issues from a repository but the operation fails because the timeout limit was exceeded. No problems with my internet connection, the repository has 50+ issues. Any ideas?

**Comment by sfdye** [comment]
Can you post the code example and detailed error message?

**Comment by Aerlinger** [comment]
I'm having a very similar issue.

Sample code:

```python
from github import Github

g = Github()

gh_repo = g.get_repo("rails/rails")

gh_issues = gh_repo.get_issues()

issues = []

# number
# user
# url
# Title
# Label
# State
# Comment count
# Assignee
# Assignees
# Created at
# Closed at
for issue in gh_issues:
  print(issue.title)
  issues.append({
    'number': issue.number,
    'user': issue.user,
    'url': issue.url,
    'title': issue.title,
    'labels': issue.labels,
    'state': issue.state,
    'comment_count': issue.comments,
    'assignee': issue.assignee,
    'assignees': issue.assignees,
    'created_at': issue.created_at,
    'closed_at': issue.closed_at
  })

import pandas as pd

pd_issues = pd.DataFrame(issues)

pd_issues.to_pickle("issues")
```

Error w/ stack trace:

```
Traceback (most recent call last):
  File "/Users/erlinger/Library/Application Support/IntelliJIdea2018.1/python/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Users/erlinger/Library/Application Support/IntelliJIdea2018.1/python/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/erlinger/Library/Application Support/IntelliJIdea2018.1/python/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/erlinger/Library/Application Support/IntelliJIdea2018.1/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/erlinger/code/AMP/amp-issues-tracking/github/analyze_issues.py", line 22, in <module>
    for issue in gh_issues:
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/site-packages/github/PaginatedList.py", line 58, in __iter__
    newElements = self._grow()
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/site-packages/github/PaginatedList.py", line 70, in _grow
    newElements = self._fetchNextPage()
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/site-packages/github/PaginatedList.py", line 172, in _fetchNextPage
    headers=self.__headers
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/site-packages/github/Requester.py", line 185, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/site-packages/github/Requester.py", line 231, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/site-packages/github/Requester.py", line 284, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/site-packages/github/Requester.py", line 309, in __requestRaw
    requestHeaders
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Users/erlinger/.pyenv/versions/3.6.1/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:733: The handshake operation timed out
```

**Comment by sfdye** [comment]
What version of PyGithub are you guys using?

**Comment by jpmartins201** [comment]
@sfdye it would be great if you could try and solve this problem, we are running out of time in a course from college - our project needs to be done due to the end of this semester - and this issue is stopping us a lot.

**Comment by sfdye** [comment]
Can you guys try the latest alpha version? see if it can solve the problem

pip install --pre --upgrade PyGithub

**Comment by jpmartins201** [comment]
This version made the requisitions a bit faster but it's still slow compared to the expected for a website.
