### ISSUE TITLE
Requires authentication problem on Test

### ISSUE THREAD

**Issue by eamanu** [PyGithub/PyGithub#822]
Hello everybody, 

I am creating a test case for the PR #809 
To do this, I created the GithubCredential.py the login and password variables with my user and password data. 

Then I run:
_python -m github.tests PullRequest.testReviewDismiss --record_

But I have this error:
```
======================================================================
ERROR: testReviewDismiss (github.tests.PullRequest.PullRequest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "github/tests/PullRequest.py", line 41, in setUp
    self.repo = self.g.get_user().get_repo("PyGithub")
  File "github/AuthenticatedUser.py", line 890, in get_repo
    "/repos/" + self.login + "/" + name
  File "github/AuthenticatedUser.py", line 226, in login
    self._completeIfNotSet(self._login)
  File "github/GithubObject.py", line 259, in _completeIfNotSet
    self._completeIfNeeded()
  File "github/GithubObject.py", line 263, in _completeIfNeeded
    self.__complete()
  File "github/GithubObject.py", line 268, in __complete
    self._url.value
  File "github/Requester.py", line 258, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "github/Requester.py", line 271, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 401 {u'documentation_url': u'https://developer.github.com/v3/users/#get-the-authenticated-user', u'message': u'Requires authentication'}
```

What I am doing wrong?
Thanks!
Regards

**Comment by sfdye** [comment]
It's probably related to #795 and this [comment](https://github.com/PyGithub/PyGithub/pull/664#issuecomment-389964369)

**Comment by sfdye** [comment]
Now that #795 is merged. Can you try again with the latest master?

**Comment by eamanu** [comment]
Ready!, I don't have the problem. I will continue working in the testcases.
Regards!
Thanks!
