### ISSUE TITLE
search user by created date

### ISSUE THREAD

**Issue by vishakraj25** [PyGithub/PyGithub#853]
Hello,
I run this lines of code to get info 
g = github.Github("USERNAME", "PASSWORD")
users=g.search_users("created:2017-11-05+vishakraj25+in:login&type=Users")
for user in users:
    print(user.login)

But It show the error..
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/github/PaginatedList.py", line 58, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python2.7/dist-packages/github/PaginatedList.py", line 70, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python2.7/dist-packages/github/PaginatedList.py", line 172, in _fetchNextPage
    headers=self.__headers
  File "/usr/local/lib/python2.7/dist-packages/github/Requester.py", line 260, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/local/lib/python2.7/dist-packages/github/Requester.py", line 271, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {u'documentation_url': u'https://developer.github.com/v3/search/', u'message': u'Validation Failed', u'errors': [{u'field': u'q', u'message': u'"2017-11-05+vishakraj25+in:login&type=Users" is not a recognized date/time format. Please provide an ISO 8601 date/time value, such as YYYY-MM-DD.', u'code': u'invalid', u'resource': u'Search'}]}
How to solve this.. Thank you

**Comment by singh811** [comment]
@vishakraj25, [this](https://github.com/PyGithub/PyGithub/blob/master/github/Requester.py#L444) is the culprit, when you search users by this **"created:2017-11-05+vishakraj25+in:login&type=Users" it** actually is encoded like **"created%3A2017-11-05%2Bvishakraj25%2Bin%3Alogin%26type%3DUsers"**.
So this is what causing the issue.
