### ISSUE TITLE
Timeout exception in request for PRs from a Repository

### ISSUE THREAD

**Issue by 0x48piraj** [PyGithub/PyGithub#919]
Refer #808

```

Traceback (most recent call last):
  File "run.py", line 28, in <module>
    if p.merged:
  File "C:\Python34\lib\site-packages\github\PullRequest.py", line 225, in merged
    self._completeIfNotSet(self._merged)
  File "C:\Python34\lib\site-packages\github\GithubObject.py", line 251, in _completeIfNotSet
    self._completeIfNeeded()
  File "C:\Python34\lib\site-packages\github\GithubObject.py", line 255, in _completeIfNeeded
    self.__complete()
  File "C:\Python34\lib\site-packages\github\GithubObject.py", line 260, in __complete
    self._url.value
  File "C:\Python34\lib\site-packages\github\Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\Python34\lib\site-packages\github\Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\Python34\lib\site-packages\github\Requester.py", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\Python34\lib\site-packages\github\Requester.py", line 277, in __requestRaw    requestHeaders
  File "C:\Python34\lib\http\client.py", line 1090, in request    self._send_request(method, url, body, headers)  
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 1230, in connect
    server_hostname=sni_hostname)
  File "C:\Python34\lib\ssl.py", line 364, in wrap_socket
    _context=self)
  File "C:\Python34\lib\ssl.py", line 578, in __init__
    self.do_handshake()
  File "C:\Python34\lib\ssl.py", line 805, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:584: The handshake operation timed out

```

**Comment by sfdye** [comment]
Please use the latest version and try again
