### ISSUE TITLE
github.GithubException.UnknownObjectException

### ISSUE THREAD

**Issue by Bluscream** [PyGithub/PyGithub#944]
```
C:\Users\blusc\AppData\Local\Programs\Python\Python36\python.exe C:/Users/blusc/PycharmProjects/github-api/main.py
Traceback (most recent call last):
  File "C:/Users/blusc/PycharmProjects/github-api/main.py", line 14, in <module>
    repo.edit(private=False)
  File "C:\Users\blusc\AppData\Local\Programs\Python\Python36\lib\site-packages\github\Repository.py", line 1284, in edit
    input=post_parameters
  File "C:\Users\blusc\AppData\Local\Programs\Python\Python36\lib\site-packages\github\Requester.py", line 262, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "C:\Users\blusc\AppData\Local\Programs\Python\Python36\lib\site-packages\github\Requester.py", line 273, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/#edit'}

Process finished with exit code 1
```

I get this for no reason? Is the library broken?

```py
from github import Github
g = Github("correctusername", "correctpassword")
repos = 0
for repo in g.get_user().get_repos():
    repo.edit(private=False)
    repos += 1
    print(repo.name)
print("Repositories processed: %s"%repos)
```

**Comment by Bluscream** [comment]
I added some prints to `C:/Users/blusc/AppData/Local/Programs/Python/Python36/Lib/site-packages/github/Repository.py`
```py
    def requestJsonAndCheck(self, verb, url, parameters=None, headers=None, input=None):
        print(verb, url, parameters, headers, input)
        return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
```
and got this:
```
GET /user/repos {} None None
PATCH https://api.github.com/repos/alex720/Stalker None None {'name': 'Stalker', 'private': False}
```

**Comment by labrys** [comment]
This may be caused by the relative imports. Python 3 requires absolute imports. This should be fixed by #967

**Comment by MikhailTH** [comment]
Same issue, no idea whats happening

**Comment by s-t-e-v-e-n-k** [comment]
@MikhailTH Would you mind opening a new issue with more detail, such as a traceback?

**Comment by arutoriusu** [comment]
I think you can write your login into `get_user()` function like this:
`for repo in g.get_user('arutoriusu').get_repos():`
Also this error may occur due trying to access private repositories. My solution - using github access token.
You can create the access token (in **github settings -> Developer settings -> Personal access tokens -> Generate new token**) and select the scope:
![image](https://user-images.githubusercontent.com/55809196/110631105-9ac0df00-81bf-11eb-8c3d-9de3efc2b014.png)
And paste token instead login and password:
`g = Github("access-token")`
I hope it hepls.
